// Iceland Ring Road 2026 — Complete Trip Data
// 16 days: Jun 30 – Jul 14 (fly home 4pm Jul 14)
// Excursions: Glacier Xtreme, Sterna bus, Drangey island, Forest Lagoon
// Removed: Canyoning, Katla ice cave, whale watching, puffin tours, Earth Lagoon (closed)
// Nights 2 & 8 now camping (Hvolsvöllur + Höfn)
// Adjusted: Days 1-5 split/expanded, Day 13 Forest Lagoon, Day 14 Drangey boat tour

const FROAD_DATA = {
  F206_Laki:{
    name:"F206/F207 — Lakagígar (Laki Craters)",
    liveUrl:"https://umferdin.is/en/road/91381",
    historical:{2021:"25 Jun",2022:"1 Jul",2023:"12 Jun",2024:"18 Jun",2025:"12 Jun"},
    earliest:"12 June", latest:"1 July", average:"20 June",
    risk:"medium", tripDay:6, tripDate:"Jul 5",
    note:"Average opening Jun 20 — likely open Jul 5 but not guaranteed. In 2022 it didn't open until July 1 (4 days before your visit). Verify at umferdin.is/en/road/91381 every morning the week before. If closed: proceed direct to Skaftafell — Day 7 is unaffected."
  },
  F208_Landmannalaugar:{
    name:"F208 north — Sigalda to Landmannalaugar",
    liveUrl:"https://umferdin.is/en",
    historical:{2021:"12 Jun",2022:"23 Jun",2023:"1 Jun",2024:"12 Jun",2025:"23 May"},
    earliest:"23 May", latest:"23 June", average:"2 June",
    risk:"low", tripDay:3, tripDate:"Jul 2",
    note:"Average opening June 2. Almost certainly open for Jul 2. Lowest risk F-road on the trip. No river crossings on the northern F208 approach from Hrauneyjar."
  },
  F88_Askja:{
    name:"F88 — Öskjuvegur (Askja / Dreki hut)",
    liveUrl:"https://umferdin.is/en",
    historical:{note:"Not in official IRCA table — typically opens late June to early July."},
    earliest:"late June", latest:"early July", average:"late June",
    risk:"low", tripDay:12, tripDate:"Jul 11",
    note:"F88 typically opens late June. By Jul 11 it has been open roughly 2–3 weeks in most years. Still check road.is and register at safetravel.is the morning of departure."
  }
};

const TRIP_DATA = {
  days:[
    // ── DAY 1 ─────────────────────────────────────────────────────────────────
    {
      num:1, date:"Jun 30", dow:"Tuesday",
      title:"Arrive Reykjavík",
      sleep:"hostel", accommodation:"Dalur HI Hostel, Sundlaugavegur 34, Laugardalur",
      tags:["hostel"], lat:64.1466, lng:-21.9426,
      summary:"Land 10:30am KEF. Collect truck — confirm F-road insurance in writing. Big Bónus grocery shop. Reykjavík on foot: Hallgrímskirkja, Sun Voyager, Harpa, hot dogs. Evening soak at Laugardalslaug geothermal pool — next door to the hostel.",
      distance:"~60km", drive:"45 min KEF to Reykjavík",
      schedule:[
        {time:"10:30am", desc:"Land at Keflavík International Airport (KEF)", note:"Allow 35–40 min for baggage and customs. Passport control queues are long in peak July."},
        {time:"11:15am", desc:"Pick up 4x4 truck at rental company", note:"CRITICAL: Confirm in writing that F88, F206, and F207 are covered by your F-road insurance. Insist on a full-size spare tyre — not a space-saver. Practice opening and closing the rooftop tent before leaving the lot. Note all existing damage on the collection form."},
        {time:"12:00pm", desc:"Drive to Reykjavík — stop at Bónus supermarket (Laugavegur 59) for the main trip grocery shop", note:"Buy for 3–4 days on the road: oats, eggs, pasta, rice, bread, hard cheese, cured meats, peanut butter, nuts, Skyr, instant coffee, cooking oil, salt. Budget ~$60 for 2 people. Buy camp gas canisters here — you cannot fly with them and Bónus is cheapest."},
        {time:"1:30pm", desc:"Check in to Dalur HI Hostel, Sundlaugavegur 34 — Laugardalur", note:"Drop bags. Free parking on site. Kitchen and café available. Bus stop directly outside for city centre (10 min). Laugardalslaug pool is 3 min walk from the front door."},
        {time:"2:30pm", desc:"Hallgrímskirkja church — climb the tower (~$11pp)", note:"Best panorama of Reykjavík. The basalt column architecture was inspired by Svartifoss waterfall — which you'll see Day 7. Notice the Leif Erikson statue outside."},
        {time:"3:30pm", desc:"Sun Voyager sculpture → Harpa concert hall waterfront walk", note:"Free. 25 min coastal walk. Harpa's facade was designed by Olafur Eliasson — walk inside. Sun Voyager is Iceland's most photographed sculpture."},
        {time:"5:00pm", desc:"Bæjarins Beztu Pylsur — hot dog stand, Tryggvagata 1", note:"Order 'eina með öllu' — ketchup, sweet mustard, remoulade, raw and fried onions. ~$4. Bill Clinton ate here. Queue moves fast."},
        {time:"6:30pm", desc:"Laugavegur street walk + any last shopping", note:"Kronán is open late for anything missed at Bónus."},
        {time:"8:00pm", desc:"Laugardalslaug geothermal pool — soak after the flight", note:"~$12pp. Iceland's largest geothermal complex: two 50m pools, multiple hot tubs, water slides, steam room, sauna. Used by locals, not tourists. Open until 10pm. 3-min walk from Dalur hostel. The best jet-lag reset available anywhere in Reykjavík."},
        {time:"10:00pm", desc:"Pack tomorrow's kit in truck cab. Alarm 7:30am.", note:"Waterproofs, snacks, water in cab — not truck bed. Day 2 is a proper drive + hike day."},
      ],
      hikes:[], excursions:[
        {name:"Laugardalslaug Geothermal Pool", operator:"laugardalslaug.is", price:"~$12pp", duration:"1.5–2 hrs",
        url:"https://www.laugardalslaug.is",
        desc:"Iceland's largest and most popular geothermal pool complex, 3 minutes walk from Dalur HI Hostel. Two 50-metre outdoor pools, multiple hot tubs at varying temperatures (36–44°C), water slides, steam room, sauna, and a dedicated children's paddling area. This is where Reykjavík locals swim — not a tourist spa. Entry ~$12pp. Open until 10pm in summer. Perfect recovery after a long-haul flight. Bring a towel and swimsuit, or rent towels on site (~$4). Locker requires a 500 ISK coin deposit."},
      ],
      tips:[
        "Iceland tap water is safe, cold, and excellent everywhere. Never buy bottled water — it's wasteful and unnecessary.",
        "Laugardalslaug is 3 minutes from Dalur hostel — do not skip it on Night 1. Hot tubs at 44°C reset the body clock better than anything else after a transatlantic flight.",
        "Midnight sun starts tonight. Bring a sleep mask or RTT blackout liner — you will need it.",
        "Orkan petrol stations are cheapest in Iceland — about 5% less than N1 and Shell. Download the Orkan app for a further 3–5% discount per litre.",
        "Iceland is essentially cashless. Pay by contactless card everywhere — ATM withdrawal fees add up unnecessarily.",
      ],
      warnings:[],
      costs:{accommodation:45, food:65, activities:11}
    },
    // ── DAY 2 ─────────────────────────────────────────────────────────────────
    {
      num:2, date:"Jul 1", dow:"Wednesday",
      title:"Háifoss Gorge + Seljalandsfoss + Hamragarðar Camp",
      sleep:"camp", accommodation:"Hamragarðar Campsite, Seljalandsfoss (Camping Card)",
      tags:["camp","hike"], lat:63.5309, lng:-20.2309,
      summary:"Route 332 to Háifoss — 122m waterfall, gorge descent to the base. Seljalandsfoss walk-behind waterfall + hidden Gljúfrabúi cave waterfall. Camp at Hamragarðar — 50m from both waterfalls, footpath from the back of the campsite.",
      distance:"~220km", drive:"~3 hrs total driving",
      schedule:[
        {time:"7:30am", desc:"Depart Reykjavík east on Ring Road (Route 1)"},
        {time:"8:45am", desc:"Turn north on Route 32 then 327/332 to Háifoss", note:"Rough gravel track. High clearance required — drive slowly. Parking ~$8 via Parka.is."},
        {time:"9:15am", desc:"Háifoss rim viewpoint — 15 min", note:"Both Háifoss (122m) and Granni waterfall visible side-by-side from the canyon edge. The canyon drops 100m+ straight down."},
        {time:"9:30am", desc:"Háifoss gorge descent hike", note:"Allow 1.5–2 hrs. Scramble into the canyon to the base of both waterfalls. Almost nobody does this. Waterproofs essential — you get soaked."},
        {time:"11:30am", desc:"Drive back to Ring Road south, then east toward Seljalandsfoss"},
        {time:"1:00pm", desc:"Seljalandsfoss — walk behind the waterfall curtain", note:"Parking ~$8. The path loops behind the waterfall — get completely surrounded by falling water. Allow 20 min."},
        {time:"1:30pm", desc:"Gljúfrabúi hidden cave waterfall — 5 min north of Seljalandsfoss", note:"FREE. Follow the cliff north — a narrow gorge opens into a cave with a waterfall dropping inside. Enter by stepping across a stream. Far fewer people know about this than Seljalandsfoss. Waterproofs useful."},
        {time:"2:00pm", desc:"Pull into Hamragarðar Campsite — set up camp", note:"Camping Card accepted. Hot showers, kitchen area, laundry, WiFi. The footpath at the rear of the site leads directly to Seljalandsfoss and Gljúfrabúi — 50m from your tent."},
        {time:"3:00pm", desc:"Shower. Rest. Lay out kit for tomorrow. Cook dinner on the camp stove."},,
        {time:"10:30pm", desc:"Walk to Seljalandsfoss via the campsite footpath — midnight sun, no crowds", note:"This is one of the great moments of the trip. Walk behind the waterfall at 11pm with the sun still above the horizon and nobody else there."},
        {time:"Late", desc:"Early night. Alarm 8:00am tomorrow — Day 3 drives to Landmannalaugar.", note:"Hamragarðar is 15 min further from Landmannalaugar than Hvolsvöllur — inconsequential on Day 3."},
      ],
      hikes:[
        {name:"Háifoss Gorge Descent", distance:"4km RT", difficulty:"Moderate", gain:"300m into canyon", time:"1.5–2 hrs",
        desc:"Háifoss's best-kept secret. From the rim, follow the canyon edge north until the scramble path appears — steep grass and scree down to the stream bed and the base of both Háifoss (122m, Iceland's 4th highest) and Granni (90m) falls side-by-side. Mist-soaked and extraordinary. Stranger Things Season 8 filmed on the rim above. Almost no tourists make this descent."},
      ],
      excursions:[],
      tips:[
        "Gljúfrabúi is one of Iceland's best-kept secrets. Enter by stepping on stones across the stream and squeezing through a narrow gorge — the waterfall drops inside a domed cave. Wear waterproofs.",
        "The midnight sun walk to Seljalandsfoss from camp is one of the best moments of the whole trip. Set an alarm for 11pm and do it.",
        "Sterna bus stop: drive 15 min west to Hvolsvöllur N1 station on Day 4 morning — easy.",
      ],
      warnings:[],
      costs:{accommodation:14, food:25, activities:0}
    },
    // ── DAY 3 ─────────────────────────────────────────────────────────────────
    {
      num:3, date:"Jul 2", dow:"Thursday",
      title:"Landmannalaugar — Rainbow Mountains",
      sleep:"camp", accommodation:"Landmannalaugar campsite (NOT on Camping Card, ~$25pp)",
      tags:["camp","hike","froad"], lat:63.9906, lng:-19.0607,
      froad:{id:"F208_Landmannalaugar", risk:"low", note:"Average opening Jun 2. Almost certainly open. No river crossings on F208 north."},
      summary:"Full day dedicated to Landmannalaugar. F208 north (no river crossings). Three hikes in the rainbow rhyolite mountains. Natural hot spring soak under the midnight sun.",
      distance:"~180km", drive:"~2.5 hrs total",
      schedule:[
        {time:"8:00am", desc:"Pack camp — drive east on Ring Road then north on Route 26"},
        {time:"9:30am", desc:"Enter F208 north at Hrauneyjar junction — drive 45 min to Landmannalaugar", note:"Clearly signed off Route 26. Zero river crossings on this route — safe for your rental. The F-road begins immediately after the junction."},
        {time:"10:15am", desc:"Arrive Landmannalaugar. Pay campsite fee and set up tent — pitches fill up.", note:"~$25pp. NOT on Camping Card. Confirm parking reservation at fi.is if arriving 9am–4pm (2026 rule)."},
        {time:"11:00am", desc:"Laugahraun lava field walk — easy 30 min warm-up", note:"Through the 1477 eruption lava bordering the campsite. Obsidian glass shards visible on the ground."},
        {time:"11:30am", desc:"Brennisteinsalda rainbow volcano loop hike"},
        {time:"1:30pm", desc:"Lunch at camp — cook on stove"},
        {time:"2:30pm", desc:"Bláhnúkur Blue Peak summit hike — best viewpoint in Landmannalaugar"},
        {time:"5:30pm", desc:"Return from summit. Eat. Rest."},
        {time:"7:00pm", desc:"Natural hot spring soak at the hut", note:"~38–40°C. Free with campsite. Change in hut changing rooms. Soak as long as you like."},
        {time:"9:00pm", desc:"Cook dinner. Download Gaia GPS trails for tomorrow (Stakkholtsgjá, Remundargil).", note:"Minimal signal at Landmannalaugar — download everything you need tonight."},
        {time:"Late", desc:"Midnight sun walk through the rhyolite valley — 11pm–1am the colours are extraordinary."},
      ],
      hikes:[
        {name:"Brennisteinsalda Loop", distance:"4km", difficulty:"Moderate", gain:"200m", time:"1.5–2 hrs",
        desc:"Circuit around the steam-venting rainbow volcano ('the sulphur wave'). Red, green, yellow, white mineral bands on the flanks. Fumaroles hiss from vents alongside the trail. Summit gives sweeping views into the valley and over the vast lava field. Marked trail — poles useful on rough sections."},
        {name:"Bláhnúkur Blue Peak", distance:"6km RT", difficulty:"Moderate–Challenging", gain:"350m", time:"2.5 hrs",
        desc:"Landmannalaugar's finest viewpoint at 943m. In every direction: red volcanoes, green obsidian lava, white snow patches, blue distant glaciers. Upper section is steep and loose — go slowly. Best in evening light when the crowds thin. Genuinely one of Iceland's great hikes."},
      ],
      excursions:[],
      tips:[
        "Don't rush Bláhnúkur — the upper loose section needs slow careful footwork. Poles make a real difference.",
        "The hot spring soak in the evening after two big hikes is one of the best moments of the trip. Your legs will thank you.",
        "Hut café sells food but it is overpriced. Cook your own.",
        "This day has no pressure or moving parts. Enjoy the pace.",
      ],
      warnings:[
        "F208 NORTH from Hrauneyjar only. Do NOT use F225 southern approach — river crossings void rental insurance.",
        "Road 332 to Háifoss (yesterday) has sharp rocks. Already done — just a reminder to drive carefully on all gravel tracks.",
      ],
      costs:{accommodation:25, food:22, parking:10}
    },
    // ── DAY 4 ─────────────────────────────────────────────────────────────────
    {
      num:4, date:"Jul 3", dow:"Friday",
      title:"Skógafoss + Þórsmörk Bus + Þakgil Canyon Camp",
      sleep:"camp", accommodation:"Þakgil Canyon Campsite (+354 893 4889 · thakgil.is)",
      tags:["camp","hike","excursion"], lat:63.5309, lng:-18.8887,
      summary:"Exit Landmannalaugar early. Skógafoss staircase and upstream river trail (hard stop 10:15am). Sterna bus to Þórsmörk — Stakkholtsgjá cave canyon is the priority hike. Camp inside Þakgil canyon with cave dining room.",
      distance:"~130km driving + bus",
      schedule:[
        {time:"7:30am", desc:"Exit Landmannalaugar via F208 south to Ring Road (~45 min)"},
        {time:"9:00am", desc:"Skógafoss — climb the 370-step staircase", note:"Parking ~$8. At the top look right (north) for the river trail path."},
        {time:"9:30am", desc:"Skógar River Trail — hike upstream", note:"HARD STOP AT 10:15am. Set an alarm. Do not let the trail absorb you — the bus cannot be missed. Push to the 5th or 6th waterfall."},
        {time:"10:15am", desc:"HARD STOP — turn around regardless of where you are on the trail."},
        {time:"10:45am", desc:"Return to parking. Drive 20 min west to Hvolsvöllur."},
        {time:"11:15am", desc:"Leave truck at Hvolsvöllur campsite or N1 station parking"},
        {time:"12:00pm", desc:"Board Sterna bus — Þórsmörk (~$44pp return)", note:"Confirm exact departure time when booking sterna.is. Bus crosses F249 river — voids rental insurance if driven. Sit right side for best river crossing views."},
        {time:"1:30pm", desc:"Arrive Þórsmörk (Volcano Huts). Begin Stakkholtsgjá canyon immediately."},
        {time:"3:30pm", desc:"Return from Stakkholtsgjá. Assess time and energy.", note:"If legs are good and time allows: start Valahnúkur summit (2.5 hrs). If not: sit in the valley and watch the glaciers — that's a perfectly full afternoon."},
        {time:"5:30pm", desc:"RETURN STERNA BUS — HARD DEADLINE", note:"Set alarm 45 min before departure. There is no later bus. Pick up truck from Hvolsvöllur campsite."},
        {time:"6:30pm", desc:"Drive east on Ring Road ~10 min, turn south on Road 214"},
        {time:"7:15pm", desc:"45-min drive up Road 214 to Þakgil", note:"NOT an F-road. Steep and unpaved but manageable. Canyon walls close in dramatically on approach."},
        {time:"8:00pm", desc:"Arrive Þakgil. Check in. Eat at cave café (Búar).", note:"Cave dining room built into the canyon cliff. Eat there tonight. Canyon walls glow gold 11pm–1am."},
      ],
      hikes:[
        {name:"Skógar River Trail Upstream", distance:"Hard stop at 10:15am", difficulty:"Moderate", gain:"300m+", time:"~45 min upstream",
        desc:"Follow the Skóga river past 10+ named waterfalls. Each more dramatic and crowd-free than the last. The trail ends at the Fimmvörðuháls volcanic pass — you won't get there today, but the first 45 minutes is extraordinary. Hard stop at 10:15am regardless of where you are."},
        {name:"Stakkholtsgjá Cave Canyon", distance:"5km RT", difficulty:"Moderate", gain:"100m", time:"2 hrs",
        desc:"The priority Þórsmörk hike. From Volcano Huts the marked path enters a narrowing slot canyon — walls close in, light reduces to a strip above, river echoes in the rock. Ends at a natural cave with a waterfall dropping from the ceiling into a pool inside. Twenty One Pilots filmed 'Jumpsuit' here. Check flood conditions on the bus."},
        {name:"Valahnúkur Summit (if time + energy)", distance:"5km", difficulty:"Moderate", gain:"300m", time:"2.5 hrs",
        desc:"Optional — only if Stakkholtsgjá is done and legs are willing. Best panorama of the valley: Eyjafjallajökull, Mýrdalsjökull, Tindfjallajökull on three sides. If you only do Stakkholtsgjá, that's a complete and excellent afternoon."},
      ],
      excursions:[
        {name:"Sterna Highland Bus — Þórsmörk Return", operator:"Sterna (sterna.is)", price:"~$44pp", duration:"Transport only",
        url:"https://www.sterna.is",
        desc:"F249 river crossings into Þórsmörk void rental car insurance on almost all policies. The Sterna bus crosses safely using purpose-modified coaches. Without this bus, Þórsmörk is inaccessible on your policy. Book at least 2 weeks ahead in July. Leave truck at Hvolsvöllur campsite or N1 station car park — free."},
      ],
      tips:[
        "The 10:15am hard stop on the Skógar river trail is the most important scheduling decision of the day. Set a phone alarm the moment you start hiking.",
        "Stakkholtsgjá is the better and more unique of the two Þórsmörk hikes. If you only do one, do this one.",
        "Þakgil cave café closes ~9:30pm. Arrive hungry.",
      ],
      warnings:[
        "DO NOT miss the return Sterna bus. There is no other way out of Þórsmörk. Set alarm 45 min before departure.",
        "DO NOT attempt to drive F249 to Þórsmörk. The river crossing voids your rental insurance.",
      ],
      costs:{accommodation:24, food:22, activities:44}
    },
    // ── DAY 5 ─────────────────────────────────────────────────────────────────
    {
      num:5, date:"Jul 4", dow:"Saturday",
      title:"Þakgil Morning Hike + Dyrhólaey Puffins + Vík",
      sleep:"hostel", accommodation:"The Barn Hostel, Vík (barnhostel.is)",
      tags:["hostel","hike"], lat:63.4190, lng:-19.0055,
      summary:"Early Remundargil canyon loop from camp with Katla glacier views. Relaxed south coast afternoon: Dyrhólaey puffin cliffs (peak July nesting), Reynisfjara black sand beach. Easy arrival at The Barn Hostel.",
      distance:"~80km",
      schedule:[
        {time:"7:00am", desc:"Remundargil canyon loop from Þakgil camp", note:"Trail map at campsite reception. Canyon in morning light is extraordinary. Early start while other campers sleep."},
        {time:"10:30am", desc:"Return to camp. Breakfast at cave café (Búar)."},
        {time:"11:30am", desc:"Pack camp, load truck, drive down Road 214 (~45 min)"},
        {time:"1:00pm", desc:"Drive to Dyrhólaey — upper lighthouse viewpoint", note:"Go to UPPER parking (lighthouse level). Look DOWN at the cliff face — puffins nest in burrows directly below, thousands of them. July = peak nesting. Parking ~$8."},
        {time:"2:00pm", desc:"Dyrhólaey sea arch — walk to the arch viewpoint"},
        {time:"3:00pm", desc:"Reynisfjara black sand beach", note:"Basalt column cave (Hálsanefshellir) accessible at low tide. See warnings."},
        {time:"4:30pm", desc:"Check in The Barn Hostel — 3.4km from Vík village", note:"barnhostel.is · +354 861 7375. Modern and stylish with huge kitchen, bar, and cinnamon rolls every morning. 5-min drive to Vík for Krónan supermarket — last proper shop before Skaftafell."},
        {time:"Evening", desc:"Walk up to Víkurkirkja (Vík church) on the hill — views over black sand and Reynisdrangar sea stacks.", note:"Free. 20 min walk from The Barn. Easily the best vantage point in the area. Bar at The Barn is open until midnight if you want a drink after."},
      ],
      hikes:[
        {name:"Remundargil Canyon Loop", distance:"12.5km", difficulty:"Moderate", gain:"250m", time:"3–4 hrs",
        desc:"From Þakgil camp, the loop follows canyon rims above the Remundargil gorge, descends into the interior, returns via the valley floor. Ridgeline gives views of Mýrdalsjökull glacier (above Katla volcano) to the north. Parts unmarked — download Wikiloc or Gaia GPS route. Bring water and snacks, nothing on route."},
      ],
      excursions:[],
      tips:[
        "Dyrhólaey puffins: upper lighthouse viewpoint, look DOWN at the cliff face. Give it 30 quiet minutes — the colony is enormous.",
        "Víkurkirkja church on the hill above Vík: the views from here are underrated and the church itself is photogenic. Worth the 20-min walk.",
      ],
      warnings:[
        "REYNISFJARA: never turn your back on the ocean. Sneaker waves kill people here every year with no warning. Stay well above the high tide line at all times.",
      ],
      costs:{accommodation:45, food:20, activities:0}
    },
    // ── DAY 6 ─────────────────────────────────────────────────────────────────
    {
      num:6, date:"Jul 5", dow:"Sunday",
      title:"Fjáðrárgljúfur Canyon + Laki Craters F206/F207",
      sleep:"camp", accommodation:"Blágil Hut Campsite (+354 487 4840)",
      tags:["camp","hike","froad"], lat:64.0707, lng:-18.2378,
      froad:{id:"F206_Laki", risk:"medium", note:"Average opening Jun 20. Likely open Jul 5 — check umferdin.is/en/road/91381 every morning this week."},
      summary:"Check F207 status first. Fjáðrárgljúfur glacial canyon. F206/F207 Laki crater field loop — 130 craters from the 1783 eruption that killed 25% of Iceland's population. Mt. Laki summit. Sleep at Blágil highland hut.",
      distance:"~200km including F-road loop",
      schedule:[
        {time:"6:30am", desc:"CHECK umferdin.is/en/road/91381 for F207 status", note:"If CLOSED: skip to Skaftafell directly. Day 7 Glacier Xtreme is completely unaffected."},
        {time:"6:45am", desc:"Register route at safetravel.is before entering F206"},
        {time:"7:00am", desc:"Depart Vík east on Ring Road"},
        {time:"7:45am", desc:"Fjáðrárgljúfur canyon — Route 206 turnoff near Kirkjubæjarklaustur", note:"Park at signed lot. Short flat walk to canyon rim. 100m-deep canyon carved by glacial meltwater. GoT Season 8. Parking ~$8."},
        {time:"8:00am", desc:"Fjáðrárgljúfur rim walk — 30–60 min"},
        {time:"8:45am", desc:"Fill fuel to MAXIMUM at Kirkjubæjarklaustur petrol station", note:"MANDATORY — zero fuel inside the F206/F207 loop."},
        {time:"9:00am", desc:"Turn north on F206 (Lakavegur)", note:"50km to Laki, ~2 hrs. Multiple river crossings. Walk every crossing before driving."},
        {time:"10:30am", desc:"Fagrifoss waterfall — short stop on F206 (free)"},
        {time:"11:30am", desc:"Arrive Laki crater ranger hut and trailhead"},
        {time:"12:00pm", desc:"Mt. Laki summit hike"},
        {time:"1:30pm", desc:"Visitor Trail through crater interior"},
        {time:"3:30pm", desc:"Drive F207 loop south"},
        {time:"5:30pm", desc:"Blágil hut campsite", note:"Call ahead: +354 487 4840. ~$15pp. NOT on Camping Card. Kitchen, toilets, showers."},
        {time:"Evening", desc:"Walk the highland plateau under the midnight sun. Total isolation."},
      ],
      hikes:[
        {name:"Mt. Laki Summit", distance:"3.5km RT", difficulty:"Moderate", gain:"200m", time:"1–1.5 hrs",
        desc:"From the ranger hut, the marked trail climbs to the summit of Mt. Laki at the centre of the 25km volcanic fissure. From the top: the entire Lakagígar crater row stretches in both directions — 130 craters in a line. The 1783 eruption was one of the most catastrophic in human history — killed 25% of Iceland's population, caused European famines, and contributed to conditions that sparked the French Revolution."},
        {name:"Visitor Trail — Crater Interior", distance:"2km loop", difficulty:"Easy", gain:"50m", time:"45 min",
        desc:"Walk directly into a crater and through the eruption fissure. 240-year-old lava covered in vivid bright green moss. The scale and absolute silence inside the crater field are staggering. Pick up the trail map at the ranger hut."},
      ],
      excursions:[],
      tips:[
        "Read about the 1783 Lakagígar eruption before visiting — the historical context transforms the experience from 'impressive volcanic landscape' to 'genuinely humbling'.",
        "Fagrifoss waterfall on F206 is a 10-min stop that most people skip. Don't — it's beautiful.",
        "Sleeping at Blágil in the highland with midnight sun is one of the atmospheric highlights of the trip.",
      ],
      warnings:[
        "CRITICAL: Check umferdin.is/en/road/91381 before departing Vík. If F206/F207 closed → drive to Skaftafell directly.",
        "Walk every river crossing before driving — never rush a ford. No mobile signal inside the loop.",
        "Register at safetravel.is before entering F206. Zero fuel inside the loop.",
      ],
      costs:{accommodation:15, food:20, fuel:35}
    },
    // ── DAY 7 ─────────────────────────────────────────────────────────────────
    {
      num:7, date:"Jul 6", dow:"Monday",
      title:"Glacier Xtreme Ice Climbing + Svartifoss",
      sleep:"camp", accommodation:"Skaftafell NP campsite (Camping Card)",
      tags:["camp","hike","excursion"], lat:64.0163, lng:-16.9681,
      summary:"Drive from Blágil to Skaftafell. Glacier Xtreme — 8.5 hours total: ice axe climbing, crevasse rappelling on Falljökull. Svartifoss basalt column waterfall at sunset. Camp Skaftafell.",
      distance:"~80km",
      schedule:[
        {time:"8:00am", desc:"Drive Blágil → Ring Road → east to Skaftafell (~1 hr)"},
        {time:"9:00am", desc:"Arrive Skaftafell. Find Arctic Adventures booking hut in car park.", note:"Parking ~$4. Wooden hut with Arctic Adventures logo at car park entrance."},
        {time:"9:00am", desc:"Glacier Xtreme check-in + gear fitting + safety briefing", note:"PRE-BOOKED at adventures.is ~$242pp. Allow 1 full hour: medical declaration, ice-climbing boot fitting (EU 36–50), crampon fitting, harness, helmet, briefing."},
        {time:"10:00am", desc:"Transport to Falljökull glacier base (20 min, included in tour)"},
        {time:"10:30am", desc:"Glacier Xtreme begins — 7 hours on Falljökull glacier"},
        {time:"5:30pm", desc:"Return transport to Skaftafell. Gear return. Rest and eat."},
        {time:"7:30pm", desc:"Svartifoss waterfall trail — easy 2 hrs, 3.5km RT", note:"Best in evening golden light. Trailhead at Skaftafell visitor centre."},
        {time:"9:30pm", desc:"Set up camp at Skaftafell. Hot showers. Laundry.", note:"Camping Card accepted. One of the best-equipped campsites on the Ring Road."},
        {time:"Late", desc:"Walk 15 min to Skaftafellsjökull glacier lagoon (free) — ice calves into the lagoon, audible at night."},
      ],
      hikes:[
        {name:"Glacier Xtreme on Falljökull (Vatnajökull)", distance:"~8km on glacier", difficulty:"Challenging", gain:"350–400m", time:"7 hrs (8.5 total with check-in)",
        desc:"Falljökull — 'Falling Glacier' — is a Vatnajökull outlet glacier named for the dramatic icefall on its upper section. You hike across the glacier surface past crevasses, moulins, and seracs to the blue ice wall where the climbing begins. Your guide selects the best wall or crevasse for conditions. You learn twin ice axe technique — the swing, the kick, the balance — then climb a vertical face of blue glacial ice. Maximum 6 people per guide. All gear provided: specialized ice-climbing boots, crampons, twin axes, harness, helmet. Bring lunch and water — glacier meltwater is drinkable directly. Most physically demanding day of the trip."},
        {name:"Svartifoss — the Black Waterfall", distance:"3.5km RT", difficulty:"Easy–Moderate", gain:"120m", time:"1.5–2 hrs",
        desc:"Drops over a curtain of dark hexagonal basalt columns — the same geological formation that inspired Hallgrímskirkja church's tower in Reykjavík. The contrast of white water against black columns is striking, especially in evening light. The marked trail passes two smaller viewpoint falls before the main drop."},
      ],
      excursions:[
        {name:"Glacier Xtreme Ice Climbing — Falljökull", operator:"Arctic Adventures (adventures.is)", price:"~$242pp", duration:"7 hrs on glacier / 8.5 hrs total",
        url:"https://adventures.is/iceland/day-tours/glacier-tours/glacier-tours-on-vatnajokull/glacier-xtreme-and-ice-climbing/",
        desc:"BOOK NOW — max 6 per group, July dates sell out within days of opening. Medical declaration required. Not suitable for back problems, heart conditions, pregnancy. Cancellation: 48-hour notice. Bring: warm merino base layer, waterproof jacket and trousers, sunglasses, lunch, 1.5L water, waterproof phone case. Ice-climbing boots provided — warmer and more rigid than hiking boots."},
      ],
      tips:[
        "Big dinner and good sleep tonight — 7 hours on a glacier is the most demanding day of the trip.",
        "Skaftafell campsite has laundry — use it after 6 days on the road.",
        "Svartifoss is best in the evening when crowds have gone and light is golden. Timing after the glacier is perfect.",
      ],
      warnings:["BOOK GLACIER XTREME NOW — the single most in-demand guided glacier activity in Iceland."],
      costs:{accommodation:16, food:20, activities:242}
    },
    // ── DAY 8 ─────────────────────────────────────────────────────────────────
    {
      num:8, date:"Jul 7", dow:"Tuesday",
      title:"Jökulsárlón Glacier Lagoon + Diamond Beach + Höfn",
      sleep:"camp", accommodation:"Höfn Camping (Camping Card)",
      tags:["camp"], lat:64.2621, lng:-15.2124,
      summary:"Morning at Jökulsárlón — walk the lagoon bridge, watch icebergs calve. Diamond Beach black sand with translucent ice chunks. Relaxed drive to Höfn. Langoustine dinner. Easy day between the glacier climb and the east fjords.",
      distance:"~110km",
      schedule:[
        {time:"8:30am", desc:"Drive east from Skaftafell to Jökulsárlón glacier lagoon (~45 min)"},
        {time:"9:15am", desc:"Jökulsárlón glacier lagoon — walk the bridge and lagoon shore", note:"FREE. The lagoon is vast — icebergs calve off Breiðamerkurjökull glacier and float slowly toward the sea. Seals often pop up between the bergs. Spend as long as you want here — no tour needed, just walk and watch."},
        {time:"10:30am", desc:"Diamond Beach (Breiðamerkursandur) — 15 min walk east across the road", note:"FREE. Ice chunks from the lagoon wash up and melt on the black sand. Some are car-sized and translucent blue. Extraordinary contrast of white ice on black volcanic sand."},
        {time:"11:30am", desc:"Drive east to Höfn (~1 hr)"},
        {time:"12:30pm", desc:"Check in Höfn Camping. Set up RTT. Shower.", note:"Camping Card accepted. Well-equipped site with harbour views. Nettó supermarket 5 min walk."},
        {time:"2:00pm", desc:"Explore Höfn harbour + Gamlabúð visitor centre (free)", note:"Small but good glacier exhibition. Walk the harbour pier for Vatnajökull ice cap views."},
        {time:"4:00pm", desc:"Rest, read, recharge — deliberate easy afternoon"},
        {time:"7:00pm", desc:"Langoustine dinner in Höfn", note:"Pakkhús at the harbour is best (~$30–35pp). Höfn is Iceland's langoustine capital — eat here properly at least once. The bisque is exceptional."},
        {time:"Late", desc:"Vatnajökull ice cap glows pale gold on clear evenings — visible from the campsite."},
      ],
      hikes:[],
      excursions:[],
      tips:[
        "Jökulsárlón is free — you don't need a kayak or boat tour to have an extraordinary experience here. The lagoon walk and the seals are reward enough.",
        "Höfn Nettó supermarket: buy supplies for the East Fjords stretch here. Next good shop is Egilsstaðir.",
        "Langoustine: even if self-catering the whole trip, eat properly here once. The Pakkhús bisque is genuinely exceptional.",
        "This is intentionally the easiest day between Day 7 (glacier climbing) and Day 9 (Lónsöræfi canyon). Use it.",
      ],
      warnings:[],
      costs:{accommodation:0, food:55}
    },
    // ── DAY 9 ─────────────────────────────────────────────────────────────────
    {
      num:9, date:"Jul 8", dow:"Wednesday",
      title:"East Fjords Coast + Stafafell + Lónsöræfi Canyon",
      sleep:"camp", accommodation:"Stafafell Nature Park (+354 699 6684)",
      tags:["camp","hike"], lat:64.4197, lng:-14.8439,
      summary:"Scenic East Fjords coastal drive over dramatic passes. Stafafell farm campsite — possibly the most peaceful camp of the trip. Lónsöræfi red rhyolite canyon — Iceland's most overlooked highland, virtually zero visitors.",
      distance:"~180km",
      schedule:[
        {time:"9:00am", desc:"Depart Höfn north on Ring Road — East Fjords coastal drive", note:"Winding road over multiple fjord passes with ocean views. Stop whenever the scenery demands it — no schedule pressure today."},
        {time:"11:30am", desc:"Arrive Stafafell Nature Park. Call ahead: +354 699 6684", note:"Tiny family-run farm campsite in a sheltered valley. You may be the only guests."},
        {time:"12:00pm", desc:"Cook lunch at camp. Rest. Load day pack."},
        {time:"1:30pm", desc:"Begin Lónsöræfi Hvítserkur canyon hike via F985 track"},
        {time:"6:30pm", desc:"Return from canyon. Cook dinner at camp."},
        {time:"Evening", desc:"Total silence, extraordinary rhyolite views. Let the legs recover."},
      ],
      hikes:[
        {name:"Lónsöræfi Hvítserkur Red Rhyolite Canyon", distance:"8–15km", difficulty:"Moderate", gain:"400m", time:"4–5 hrs",
        desc:"Iceland's most overlooked highland area. Jagged rust-red and orange rhyolite peaks rising from a hidden valley. Sees a fraction of the visitors that Landmannalaugar gets, but equally extraordinary — just without the crowds. Access via F985 from Stafafell (mild track, manageable in dry conditions). Trail unmarked in sections — download Gaia GPS beforehand. Water from mountain streams only: bring Sawyer Squeeze filter. Best in evening light when the colours intensify."},
      ],
      excursions:[],
      tips:[
        "Lónsöræfi in evening light (7–9pm) is genuinely special. The rhyolite changes from orange to deep red as the sun drops angle.",
        "Stafafell is the most peaceful camp of the trip. No phone signal. Complete isolation.",
        "This is the cheapest day of the trip — campsite and a hike. Embrace the simplicity.",
      ],
      warnings:[
        "Lónsöræfi trail is partially unmarked. Download Gaia GPS route before leaving Höfn. Bring water filter.",
      ],
      costs:{accommodation:14, food:18}
    },
    // ── DAY 10 ────────────────────────────────────────────────────────────────
    {
      num:10, date:"Jul 9", dow:"Thursday",
      title:"Stuðlagil Canyon + Seyðisfjörður + Egilsstaðir Resupply",
      sleep:"hostel", accommodation:"Vinland Camping Pods, Fellabær, Egilsstaðir (booking.com)",
      tags:["hostel","hike"], lat:65.2590, lng:-14.3952,
      summary:"Stuðlagil basalt column canyon — turquoise river, 30m hexagonal columns, still undervisited internationally. Seyðisfjörður rainbow road and blue church. Major resupply at Egilsstaðir.",
      distance:"~200km",
      schedule:[
        {time:"9:00am", desc:"Depart Stafafell north on Ring Road"},
        {time:"9:30am", desc:"Check upstream weather before committing to Stuðlagil", note:"Heavy rain upstream = white opaque river, not turquoise. Check on phone now. If white, skip and add time at Seyðisfjörður instead."},
        {time:"10:00am", desc:"Turn north on Route 923 to Stuðlagil Canyon (~45 min from Ring Road)"},
        {time:"11:00am", desc:"Stuðlagil Canyon east rim hike — go to EAST car park", note:"The east rim is the iconic viewpoint. 30m basalt columns rising from turquoise river."},
        {time:"2:30pm", desc:"Drive back to Ring Road, north and east over mountain pass to Seyðisfjörður (~1.5 hrs)"},
        {time:"4:00pm", desc:"Seyðisfjörður — rainbow road, blue church, café stop", note:"45–60 min. Rainbow-painted road leads to Bláa Kirkjan blue church. Artists' village. Skaftfell Bistro has excellent food."},
        {time:"5:30pm", desc:"Drive back to Egilsstaðir (~45 min)"},
        {time:"6:15pm", desc:"Check in Vinland Camping Pods (Fellabær — 2km from Egilsstaðir centre). MAJOR RESUPPLY.", note:"Bónus supermarket and Orkan fuel in Egilsstaðir. Laundry at pods. Last proper shop until Akureyri. Bring your own sleeping bag — bed linen not included (or rent on-site ~$15). Breakfast at Lake Hotel Egilsstaðir 1.2km away."},
      ],
      hikes:[
        {name:"Stuðlagil Canyon East Rim", distance:"4–8km RT", difficulty:"Easy–Moderate", gain:"100m", time:"2–4 hrs",
        desc:"Hexagonal basalt columns rising 30m from a turquoise glacial river. The canyon was entirely underwater until 2009 when a hydroelectric dam upstream dropped the river level, revealing the columns. Go to the EAST car park for the iconic viewpoint. Early morning or evening gives the best turquoise colour — heavy rain upstream turns the river white and opaque. Walk as far as Stuðlafoss waterfall for the best views."},
      ],
      excursions:[],
      tips:[
        "East car park for Stuðlagil — the west side viewpoint is inferior. Don't be fooled by GPS routing to the wrong side.",
        "Seyðisfjörður: the Skaftfell Bistro has genuinely excellent food. The village has an artist community feel and the ferry to mainland Europe departs on Thursdays.",
        "Egilsstaðir resupply is critical. Next reliable supermarket is Akureyri.",
      ],
      warnings:[
        "Check river colour before driving the Route 923 detour — white water after rain means no reward for the detour.",
      ],
      costs:{accommodation:45, food:25}
    },
    // ── DAY 11 ────────────────────────────────────────────────────────────────
    {
      num:11, date:"Jul 10", dow:"Friday",
      title:"Mývatn — Volcanic Wonderland (All Free)",
      sleep:"camp", accommodation:"Hlíð Campsite, Lake Mývatn (Camping Card)",
      tags:["camp","hike"], lat:65.6495, lng:-16.9187,
      summary:"Goðafoss waterfall. Hverfjall perfectly circular crater rim hike. Dimmuborgir lava tower formations. Grjótagjá Game of Thrones cave hot spring. All free. Head nets mandatory.",
      distance:"~200km from Egilsstaðir",
      schedule:[
        {time:"8:00am", desc:"Depart Egilsstaðir west on Ring Road (~175km, 2.5 hrs)", note:"Buy head nets HERE before leaving if you don't have them. Egilsstaðir is your last reliable shop before Mývatn."},
        {time:"10:00am", desc:"Goðafoss — Waterfall of the Gods (free, 30–45 min)", note:"Right off Ring Road. 12m high, 30m wide. In 1000 AD Iceland voted to adopt Christianity and the lawspeaker threw Norse god idols into these falls."},
        {time:"11:00am", desc:"Hverfjall volcano crater rim hike", note:"Parking ~$8. STAY ON MARKED PATH — tephra is permanently damaged by off-path footsteps."},
        {time:"1:30pm", desc:"Dimmuborgir lava formations (free, 30–90 min)", note:"Take the 'Church' loop for the most dramatic towers and arches."},
        {time:"3:00pm", desc:"Grjótagjá lava cave hot spring (free, 30 min)", note:"The GoT cave (Jon Snow and Ygritte, Season 3). Too hot to swim (~50°C) but the electric blue glow is extraordinary. Bring a small torch."},
        {time:"4:30pm", desc:"Check in Hlíð campsite. HEAD NETS ON IMMEDIATELY.", note:"Camping Card accepted. Do not delay — midges are immediate the moment you exit the truck."},
        {time:"6:00pm", desc:"Cook dinner at camp. Walk lake shore (head nets on)."},
        {time:"Late", desc:"Mývatn lake in midnight light — extraordinary golden reflections."},
      ],
      hikes:[
        {name:"Hverfjall Crater Rim Loop", distance:"3km loop", difficulty:"Moderate", gain:"150m", time:"1.5–2 hrs",
        desc:"Hverfjall is a near-perfect circular tephra cone, 1km wide, formed in a single eruption 2,700 years ago. The rim hike circles the full crater with views into the 1km-wide interior bowl and out over Lake Mývatn. The tephra surface is extremely fragile — permanent damage from a single footstep takes centuries to recover. Marked path only. Best in late-evening light when the lake turns golden."},
      ],
      excursions:[],
      tips:[
        "Head nets at Mývatn are not optional — they are survival gear. Buy before arriving. Midges fly into eyes, ears, mouth constantly without them.",
        "Grjótagjá: both cave chambers are accessible. The electric blue glow from refracted light is the experience. Temperature near 50°C — don't enter the water.",
        "Earth Lagoon Mývatn is closed for 2026 renovation — no paid lagoon today. All free day, which actually takes the pressure off.",
      ],
      warnings:[
        "MIDGES: open the tent zip and they're inside in 10 seconds. Head nets on the moment you step outside at camp.",
        "Stay on marked paths at Hverfjall — off-path footsteps permanently scar the tephra surface.",
      ],
      costs:{accommodation:16, food:18}
    },
    // ── DAY 12 ────────────────────────────────────────────────────────────────
    {
      num:12, date:"Jul 11", dow:"Saturday",
      title:"F88 to Askja Caldera + Viti Crater Swim — Dreki Camp",
      sleep:"camp", accommodation:"Dreki Hut Campsite (ffa.is — NOT Camping Card, ~$18pp)",
      tags:["camp","hike","froad"], lat:65.0421, lng:-16.5952,
      froad:{id:"F88_Askja", risk:"low", note:"F88 typically opens late June. By Jul 11 should have been open ~2–3 weeks. Still check road.is morning of."},
      summary:"Fill fuel + 20L jerry can at Mývatn — mandatory. F88 through the world's largest lava field (Ódáðahraun) to Askja. 8km caldera hike. Swim in Viti geothermal crater. Sleep at Dreki under midnight sun.",
      distance:"~120km each way on F88",
      schedule:[
        {time:"7:00am", desc:"FILL FUEL TO ABSOLUTE MAXIMUM at Mývatn + fill 20L jerry can", note:"MANDATORY. F88 is ~120km each way on rough highland road. Your 4x4 burns extra on gravel. Zero fuel available between Mývatn and Ring Road exit."},
        {time:"7:30am", desc:"Register at safetravel.is — F88 to Askja and return"},
        {time:"8:00am", desc:"Enter F88 junction (~20km east of Mývatn on Ring Road)", note:"Allow 2.5 hrs to Dreki. Max 40km/h. The landscape transforms immediately into the dark volcanic Ódáðahraun lava desert."},
        {time:"10:30am", desc:"Arrive Dreki hut. Sign in with rangers. Leave truck.", note:"Rangers track visitors and can advise on trail conditions. Buy snacks and water on site."},
        {time:"11:00am", desc:"Begin Askja caldera hike"},
        {time:"2:30pm", desc:"Viti crater — swim in geothermal crater lake (25–27°C, free)", note:"Path down is steep and slippery — poles essential. Change at truck before hiking, bring towel and dry clothes."},
        {time:"4:00pm", desc:"Return to Dreki. Set up camp."},
        {time:"5:00pm", desc:"Cook big meal — high calories after a demanding day."},
        {time:"Late", desc:"Midnight sun in the highland lava desert — golden light at 1–2am. Set an alarm."},
      ],
      hikes:[
        {name:"Askja Caldera Hike + Viti Crater Swim", distance:"8km RT from Dreki", difficulty:"Moderate", gain:"200m", time:"3–4 hrs",
        desc:"Trail from Dreki crosses ancient lava fields to the Askja caldera rim — Öskjuvatn lake fills the caldera, deep cold blue, formed after the catastrophic 1875 eruption. Continue 15 min to Viti: 1875 explosion crater, 150m wide, containing warm geothermal water at 25–27°C, milky green-blue from minerals. The path down to the water is steep and slippery — poles essential. Swimming inside an active volcanic crater in the highland lava desert is one of the genuinely great experiences of the entire trip."},
      ],
      excursions:[],
      tips:[
        "The F88 drive through Ódáðahraun (world's largest lava field, 3,000 km²) is as remarkable as the caldera itself. Stop and walk out onto the lava — the silence is total.",
        "Viti swim: bring a waterproof bag for your phone — the colours inside the crater are extraordinary and worth photographing.",
        "Midnight at Dreki: the golden light on the lava desert at 1–2am is something else. Set an alarm if you want to catch it.",
      ],
      warnings:[
        "CRITICAL: Fill fuel to maximum + 20L jerry can at Mývatn before entering F88. Zero fuel on this route.",
        "Walk every river crossing before driving — never rush a ford.",
        "Bring warm layers — altitude makes it significantly colder than the Ring Road.",
      ],
      costs:{accommodation:18, food:22, fuel:98}
    },
    // ── DAY 13 ────────────────────────────────────────────────────────────────
    {
      num:13, date:"Jul 12", dow:"Sunday",
      title:"Exit F88 + Akureyri Rest Day + Forest Lagoon",
      sleep:"hostel", accommodation:"Hafnarstræti Hostel, Akureyri (Hafnarstræti 99-101)",
      tags:["hostel","excursion"], lat:65.6814, lng:-18.0898,
      summary:"Drive F88 back to Ring Road. Akureyri: laundry, resupply, botanical garden, reindeer burger. Evening at Forest Lagoon — infinity pools over Eyjafjörður fjord in the birch forest. Full rest day after two highland camps.",
      distance:"~240km",
      schedule:[
        {time:"8:00am", desc:"Exit F88 — same road back, 2.5 hrs to Ring Road"},
        {time:"10:30am", desc:"Fill fuel at first Ring Road station"},
        {time:"12:00pm", desc:"Drive Ring Road west to Akureyri (~90 min)"},
        {time:"1:30pm", desc:"Check in Hafnarstræti Hostel, Hafnarstræti 99-101. Laundry. Long shower.", note:"Japanese-style capsule pods. Self check-in — confirm door code received by email before departure from Dreki. Laundry on site."},
        {time:"3:00pm", desc:"Akureyri Botanical Garden (Lystigarðurinn) — free", note:"World's most northerly botanical garden. Remarkable in full July bloom. 15 min walk from centre."},
        {time:"4:30pm", desc:"Walk Akureyri waterfront and city centre", note:"Heart-shaped traffic lights are the local quirk. Compact and charming."},
        {time:"7:00pm", desc:"Reindeer burger at Akureyri Backpackers restaurant (~$22pp)", note:"Legendary among Ring Road travellers. Large portion."},
        {time:"8:30pm", desc:"Drive to Forest Lagoon, Vaðlaskógur forest (~10 min from centre)", note:"forestlagoon.is. PRE-BOOK. Free shuttle also from Hof cultural centre hourly. Open until midnight in July."},
        {time:"9:00pm", desc:"Forest Lagoon — infinity pools over Eyjafjörður fjord in birch forest", note:"~$44–52pp. Two geothermal infinity pools (37–40°C), Finnish sauna, cold plunge, swim-up bars. Towel rental ~$7."},
        {time:"11:00pm", desc:"Return to guesthouse. Resupply at Bónus if open (check hours)."},
      ],
      hikes:[],
      excursions:[
        {name:"Forest Lagoon Geothermal Spa", operator:"Forest Lagoon (forestlagoon.is)", price:"~$44–52pp (5,990–7,150 ISK)", duration:"2–3 hrs",
        url:"https://www.forestlagoon.is",
        desc:"Opened 2022, the Forest Lagoon was born from a happy accident: workers digging the Vaðlaheiðargöng road tunnel in 2015 struck a natural hot spring beneath the mountain. The complex features two geothermal infinity pools overlooking Eyjafjörður fjord, set among birch and pine trees in Vaðlaskógur forest. The infinity edge drops straight to the fjord view — from the water you look out over the fjord with mountains behind Akureyri. Finnish sauna, cold plunge, two swim-up bars, and a bistro. Far less crowded and more intimate than the Blue Lagoon. An evening slot in the midnight sun here is one of the great North Iceland experiences. Book in advance at forestlagoon.is or email reservations@forestlagoon.is. Towels not included — rent for ~$7 or bring your own."},
      ],
      tips:[
        "Forest Lagoon evening slot: the midnight sun over Eyjafjörður from the infinity pool is extraordinary. Book the 8:30 or 9pm session.",
        "Akureyri is the largest town outside Reykjavík — enjoy the infrastructure. It's the last proper city until you fly home.",
        "This is a full rest day. Don't overschedule — two highland camp nights followed by a long drive day tomorrow means rest is valuable.",
      ],
      warnings:[],
      costs:{accommodation:55, food:30, activities:48}
    },
    // ── DAY 14 ────────────────────────────────────────────────────────────────
    {
      num:14, date:"Jul 13", dow:"Monday",
      title:"Kolugljúfur Canyon + Snæfellsnes — Kirkjufell midnight",
      sleep:"hostel", accommodation:"North Star Guesthouse Snæfellsnes, Ólafsvík (+354 487 1212)",
      tags:["hostel","hike"], lat:64.8956, lng:-23.7180,
      summary:"Kolugljúfur hidden gorge and upward-spraying waterfall. Long drive west to Snæfellsnes. Ytri Tunga harbour seals. Kirkjufell at golden hour. North Star Guesthouse, Ólafsvík. Midnight drive back to Kirkjufell for the golden light.",
      distance:"~260km",
      schedule:[
        {time:"8:30am", desc:"Depart Akureyri west on Ring Road"},
        {time:"10:00am", desc:"Turn south on Route 715 to Kolugljúfur canyon (free)"},
        {time:"10:30am", desc:"Kolugljúfur canyon walk — 30–60 min", note:"No guardrails. Care near edge. In strong wind the main waterfall blows upward — one of Iceland's strangest and most underrated sights."},
        {time:"11:30am", desc:"Continue west and south on Ring Road toward Snæfellsnes (~200km, ~2.5 hrs)"},
        {time:"2:00pm", desc:"Turn onto Route 54 west into Snæfellsnes peninsula"},
        {time:"3:00pm", desc:"Ytri Tunga — harbour seal colony (free, 20 min)", note:"Signed off Route 54. Short walk to rocky point. Grey and harbour seals haul out here in large numbers. Move slowly and stay low."},
        {time:"4:00pm", desc:"Grundarfjörður — Kirkjufell mountain + Kirkjufellsfoss viewpoint (free)", note:"The most photographed mountain in Iceland. Walk to the three-stream waterfall with the peak behind."},
        {time:"5:30pm", desc:"Drive 20 min east to Ólafsvík. Check in North Star Guesthouse.", note:"+354 487 1212. All rooms with private bathroom. Bar and lounge. Confirm check-in code received in advance — self check-in after hours."},
        {time:"7:00pm", desc:"Explore Ólafsvík harbour + Pakkhús regional museum (free)", note:"Compact fishing village with a striking triangular church. The Gufuskálar radio mast — Iceland's tallest structure at 412m — is visible to the west."},
        {time:"9:00pm", desc:"Cook dinner or eat at local restaurant in Ólafsvík"},
        {time:"11:30pm", desc:"Drive 20 min west to Kirkjufell for midnight golden light", note:"Mountain glows gold 11:30pm–1am. The great photographic moment of Snæfellsnes and one of the genuine highlights of the trip."},
      ],
      hikes:[
        {name:"Kolugljúfur Canyon Walk", distance:"1.5km", difficulty:"Easy", gain:"50m", time:"30–60 min",
        desc:"'Kola's Gorge' — carved into red-orange basalt by the Víðidalsá river. Multiple waterfalls in the gorge. The standout: in strong wind one waterfall is blown upward by canyon air currents, spraying skyward. Completely unknown to most international visitors. Free. No guardrails."},
      ],
      excursions:[],
      tips:[
        "Kirkjufell midnight: set an alarm for 11:30pm. 20-minute drive from North Star. The golden light on this mountain is one of Iceland's iconic photographic moments.",
        "Ytri Tunga seals: move slowly, stay low, don't rush — they watch calmly if you're patient.",
        "North Star Guesthouse: confirm check-in door code by email before leaving Akureyri. Self check-in after 4pm.",
      ],
      warnings:[
        "Kolugljúfur: no guardrails on the canyon rim. Take care near the edge.",
        "Day 14 is a long drive day (~260km). Start by 8:30am from Akureyri.",
      ],
      costs:{accommodation:70, food:25, activities:0}
    },
    // ── DAY 15 ────────────────────────────────────────────────────────────────
    {
      num:15, date:"Jul 14", dow:"Tuesday",
      title:"Snæfellsjökull + Arnarstapi + Seltún → KEF 4pm",
      sleep:"—", accommodation:"Flight departs KEF 4:00pm",
      tags:["hike"], lat:63.8958, lng:-22.0548,
      summary:"Arnarstapi coastal trail and Gatklettur circular arch. Snæfellsjökull National Park glacier tip — Jules Verne's Journey to the Centre of the Earth. Seltún geothermal mud pots en route. Return truck. 4pm departure.",
      distance:"~250km",
      schedule:[
        {time:"7:30am", desc:"Arnarstapi — coastal trail + Gatklettur arch hike (1.5 hrs)"},
        {time:"9:30am", desc:"Hellnar viewpoint + basalt shore walk (15 min)"},
        {time:"10:00am", desc:"Drive to Snæfellsjökull NP glacier tip — free drive-in", note:"Route 574 along the peninsula tip. Jules Verne set Journey to the Centre of the Earth here. Arctic fox tracks sometimes visible on snow near the glacier."},
        {time:"10:30am", desc:"OPTIONAL: Vatnshellir lava cave guided tour (~$20pp, 45 min)", note:"8,000-year-old lava tube, signed on Route 574. Tours depart hourly. Book on-site. Cave temperature ~4°C — warm layer essential."},
        {time:"11:15am", desc:"LEAVE SNÆFELLSNES — hard deadline for 4pm flight", note:"No exceptions. Drive south on Route 54, east on Ring Road, south toward Reykjanes (~2 hrs)."},
        {time:"1:15pm", desc:"Seltún geothermal area, Reykjanes peninsula (25 min stop)", note:"FREE. Exit toward Krýsuvík. Boardwalk through bubbling mudpots, steaming fumaroles, sulphur-stained earth. Adds only 20 min. Worth every second."},
        {time:"1:45pm", desc:"Fill fuel at Orkan on Reykjanesbraut before rental return", note:"Most contracts require full tank. Fill before the airport."},
        {time:"2:00pm", desc:"Return truck to KEF rental lot", note:"Allow minimum 2 hours before departure. Clean truck bed. Fold and latch RTT correctly. Note any damage before they do."},
        {time:"2:30pm", desc:"Terminal check-in + security", note:"KEF security can be very long in peak July. Allow 60 min minimum."},
        {time:"3:00pm", desc:"Duty-free at KEF", note:"Brennivín (the Black Death caraway aquavit), Icelandic gin, skyr chocolate, Nói Síríus chocolate, lopapeysa wool. VAT refund desk near Arrivals."},
        {time:"4:00pm", desc:"FLIGHT DEPARTS. Iceland done."},
      ],
      hikes:[
        {name:"Arnarstapi–Hellnar Coastal Trail + Gatklettur Arch", distance:"5km RT", difficulty:"Easy", gain:"50m", time:"1.5 hrs",
        desc:"One of Iceland's best short coastal walks. Path follows lava coastline between the two villages past basalt sea stacks, sea arches, caves, and seabird colonies. Gatklettur ('Hole Rock') — a perfect circular arch through solid basalt promontory, framing ocean beyond — is the centrepiece. Fulmars, kittiwakes, Arctic terns nesting on every ledge. From Hellnar, a short detour leads to a sheltered sea cave at low tide."},
      ],
      excursions:[],
      tips:[
        "Leave Snæfellsnes by 11:15am — the 4pm flight has no margin for delay.",
        "Vatnshellir lava cave adds 45 min. Only do it if you're ahead of schedule. No advance booking needed.",
        "Seltún is directly on the route to KEF and adds only 20 min — genuinely worth not skipping.",
        "KEF duty-free: Brennivín is the classic Icelandic spirit. Much cheaper here than anywhere in Iceland.",
        "Return truck: rental companies charge for dirty truck beds. Sweep it out. Check for damage.",
      ],
      warnings:[
        "HARD DEADLINE: flight 4:00pm. Leave Snæfellsnes tip by 11:15am. Return truck by 2:00pm. Clear security by 3:00pm.",
        "Fill fuel before rental return — most contracts require a full tank.",
      ],
      costs:{food:20}
    },
  ],

  regions:{
    south:[1,2,3,4,5,6,7,8],
    east:[8,9,10],
    north:[11,12,13,14],
    west:[14,15],
  },

  budget:{
    fixed:[
      {label:"4x4 truck rental — 15 days, F-road insurance", sub:"Confirm F88 + F206/F207 in writing. Full-size spare tyre.", pp:675, total:1350},
      {label:"Iceland Camping Card — 2 adults, 28 nights", sub:"campingcard.is — covers Skaftafell, Hlíð Mývatn, and others.", pp:94, total:187},
      {label:"Travel insurance — must cover glacier ice climbing", sub:"Confirm Glacier Xtreme explicitly covered in writing.", pp:60, total:120},
    ],
    accommodation:[
      {label:"Hostel nights × 8 (avg $47pp)", sub:"Dalur HI · Barn · Vinland Pods · Hafnarstræti · North Star", pp:284, total:752},
      {label:"Camp nights × 7 (avg $17pp)", sub:"Hvolsvöllur · Höfn · Landmannalaugar · Þakgil · Blágil · Skaftafell · Stafafell · Hlíð · Dreki", pp:119, total:238},
    ],
    food:[
      {label:"15 days mixed self-catering — avg $22/day", sub:"Bónus shops. Cook from truck. 2 restaurant meals: Höfn langoustine + Akureyri reindeer burger.", pp:330, total:660},
    ],
    activities:[
      {label:"Glacier Xtreme ice climbing — Falljökull", sub:"adventures.is — BOOK NOW — Day 7", pp:242, total:484},
      {label:"Forest Lagoon — Akureyri evening", sub:"forestlagoon.is — Day 13", pp:48, total:96},
      {label:"Þórsmörk Sterna bus return", sub:"sterna.is — non-optional access — Day 4", pp:44, total:88},
      {label:"Laugardalslaug geothermal pool", sub:"Day 1 evening · next door to Dalur HI", pp:12, total:24},
      {label:"Hallgrímskirkja tower", sub:"Day 1", pp:11, total:22},
    ],
    fuel:[
      {leg:"Day 1: KEF → Reykjavík", km:60, cost:8},
      {leg:"Day 2: Reykjavík → Háifoss → Seljalandsfoss → Hvolsvöllur", km:220, cost:27},
      {leg:"Day 3: Hvolsvöllur → Landmannalaugar F208", km:180, cost:22},
      {leg:"Day 4: Landmannalaugar → Skógafoss → Þórsmörk → Þakgil", km:130, cost:16},
      {leg:"Day 5: Þakgil → Dyrhólaey → Vík", km:80, cost:10},
      {leg:"Day 6: Vík → Fjáðrárgljúfur → F206/F207 Laki → Blágil", km:200, cost:35},
      {leg:"Day 7: Blágil → Skaftafell (Glacier Xtreme)", km:80, cost:10},
      {leg:"Day 8: Skaftafell → Jökulsárlón → Diamond Beach → Höfn", km:110, cost:14},
      {leg:"Day 9: Höfn → East Fjords → Stafafell", km:180, cost:22},
      {leg:"Day 10: Stafafell → Stuðlagil → Seyðisfjörður → Egilsstaðir", km:200, cost:25},
      {leg:"Day 11: Egilsstaðir → Goðafoss → Mývatn", km:175, cost:22},
      {leg:"Day 12: Mývatn → F88 → Askja → Dreki and back", km:240, cost:49},
      {leg:"Day 13: Dreki → F88 exit → Akureyri", km:200, cost:25},
      {leg:"Day 14: Akureyri → Kolugljúfur → Snæfellsnes", km:320, cost:40},
      {leg:"Day 15: Snæfellsnes → Seltún → KEF", km:210, cost:26},
    ],
    parking:[
      {site:"Háifoss / Road 332 (Day 2)", cost:8},
      {site:"Seljalandsfoss (Day 2)", cost:4},
      {site:"Skógafoss (Day 4)", cost:4},
      {site:"Skaftafell NP (Day 7)", cost:4},
      {site:"Diamond Beach (Day 8)", cost:4},
      {site:"Fjáðrárgljúfur canyon (Day 6)", cost:4},
      {site:"Dyrhólaey + Reynisfjara (Day 5)", cost:8},
      {site:"Hverfjall, Mývatn (Day 11)", cost:4},
      {site:"Stuðlagil Canyon (Day 10)", cost:4},
      {site:"Snæfellsjökull NP + Arnarstapi (Day 15)", cost:8},
      {site:"Seltún, Reykjanes (Day 15)", cost:3},
      {site:"Goðafoss (Day 11)", cost:3},
      {site:"Misc Ring Road pullouts", cost:10},
    ],
  },

  checklist:[
    {section:"Book immediately — do today", badge:"urgent", items:[
      {text:"Glacier Xtreme ice climbing — Falljökull / Vatnajökull", sub:"Day 7 (Jul 6) · ~$242pp · Max 6 people · July sells out within days of opening", url:"https://adventures.is/iceland/day-tours/glacier-tours/glacier-tours-on-vatnajokull/glacier-xtreme-and-ice-climbing/"},
      {text:"Dalur HI Hostel, Reykjavík — Sundlaugavegur 34", sub:"Night 1 (Jun 30) · hostel.is", url:"https://www.hostel.is"},
      
      {text:"Þakgil canyon campsite", sub:"Night 4 (Jul 3) · thakgil.is or +354 893 4889", url:"https://www.thakgil.is"},
      {text:"Sterna highland bus — Þórsmörk return", sub:"Day 4 (Jul 3) · $44pp · must pre-book · sterna.is", url:"https://www.sterna.is"},
    ]},
    {section:"Book within 1–2 weeks", badge:"soon", items:[
      {text:"Vinland Camping Pods, Fellabær", sub:"Night 10 (Jul 9) · booking.com", url:"https://www.booking.com"},
      {text:"Hafnarstræti Hostel, Akureyri", sub:"Night 13 (Jul 12) · Hafnarstræti 99-101 · confirm self check-in code"},
      {text:"North Star Guesthouse, Ólafsvík", sub:"Night 14 (Jul 13) · guidetoiceland.is · +354 487 1212", url:"https://www.guidetoiceland.is · +354 487 1212"},
      {text:"Forest Lagoon, Akureyri — evening slot", sub:"Day 13 (Jul 12) evening · ~$44–52pp · forestlagoon.is", url:"https://www.forestlagoon.is"},
      {text:"Landmannalaugar parking reservation (if arriving 9am–4pm)", sub:"Day 3 (Jul 2) · fi.is mountain huts page", url:"https://www.fi.is/en/mountain-huts/all-mountain-huts/landmannalaugar"},
    ]},
    {section:"Accommodation contacts — all 15 nights", badge:"info", items:[
      {text:"Night 1 — Dalur HI Hostel, Sundlaugavegur 34, Laugardalur", sub:"+354 553 8110 · hostel.is · free parking · Laugardalslaug pool next door"},
      {text:"Night 2 — Hamragarðar Campsite, Seljalandsfoss", sub:"Camping Card accepted · footpath to both waterfalls · hot showers + laundry · right by Sterna bus stop"},
      {text:"Night 3 — Landmannalaugar campsite", sub:"+354 860 3335 · fi.is · NOT on Camping Card · ~$25pp · pay at hut"},
      {text:"Night 4 — Þakgil canyon campsite", sub:"+354 893 4889 · thakgil.is · cave dining room · hot showers"},
      {text:"Night 5 — The Barn Hostel, Vík", sub:"barnhostel.is · fills fast · kitchen available"},
      {text:"Night 6 — Blágil hut campsite (F207 loop)", sub:"+354 487 4840 · NOT on Camping Card · ~$15pp"},
      {text:"Night 7 — Skaftafell NP campsite", sub:"Camping Card accepted · hot showers + laundry"},
      {text:"Night 8 — Höfn Camping", sub:"Camping Card accepted · harbour views · Nettó supermarket 5 min walk"},
      {text:"Night 9 — Stafafell Nature Park", sub:"+354 699 6684 · call to confirm open · ~$14pp"},
      {text:"Night 10 — Vinland Camping Pods, Fellabær", sub:"booking.com · bring own sleeping bag · bed linen rental ~$15"},
      {text:"Night 11 — Hlíð campsite, Lake Mývatn", sub:"+354 899 6203 · Camping Card · HEAD NETS ESSENTIAL"},
      {text:"Night 12 — Dreki hut campsite (F88/F910 junction)", sub:"ffa.is · NOT on Camping Card · ~$18pp · rangers on site"},
      {text:"Night 13 — Hafnarstræti Hostel, Akureyri", sub:"Hafnarstræti 99-101 · self check-in · confirm door code before leaving Dreki"},
      {text:"Night 14 — North Star Guesthouse Snæfellsnes, Ólafsvík", sub:"+354 487 1212 · confirm check-in code in advance"},
    ]},
    {section:"Call / confirm before departure", badge:"before", items:[
      {text:"Rental company: F-road insurance in writing — F88, F206, F207", sub:"Full-size spare tyre (not space-saver). RTT height clears campsite barriers."},
      {text:"Stafafell campsite open Jul 8 — +354 699 6684"},
      {text:"Blágil hut campsite available Jul 5 — +354 487 4840"},
      {text:"Travel insurance: glacier ice climbing explicitly covered", sub:"Call insurer, confirm Glacier Xtreme covered in writing before departure."},
    ]},
    {section:"Purchase before departure", badge:"before", items:[
      {text:"Iceland Camping Card — 2 adults, 28 nights", sub:"€179 / ~$187 · campingcard.is", url:"https://www.campingcard.is"},
      {text:"Head nets × 2 (sealed face type)", sub:"ABSOLUTELY ESSENTIAL for Mývatn, Day 11. Buy at REI or Amazon before leaving."},
      {text:"Water filter — Sawyer Squeeze or BeFree", sub:"For Lónsöræfi canyon (Day 9) and Askja highland (Day 12)."},
      {text:"Blackout sleep mask × 2", sub:"Midnight sun never gets dark in July. Essential from Night 1."},
      {text:"20-litre fuel jerry can (HDPE approved)", sub:"Fill at Mývatn before F88 on Day 12. Mandatory."},
      {text:"Tow rope — rated to vehicle weight + 50%", sub:"Minimum 5-tonne. Buy before leaving — expensive in Iceland."},
      {text:"Tyre plug kit + portable 12V inflator", sub:"For F-road lava punctures."},
      {text:"First aid kit (adventure-rated)", sub:"Compeed blisters, bandages, antiseptic, pain relief, antihistamine."},
      {text:"Trekking poles × 2 pairs", sub:"Essential for Viti crater descent (slippery), Bláhnúkur, Lónsöræfi."},
    ]},
    {section:"Download + bookmark", badge:"before", items:[
      {text:"Parka.is — set up account + payment before landing", sub:"Camera-enforced parking at ALL major Iceland sites.", url:"https://parka.is"},
      {text:"112 Iceland app", sub:"One button sends GPS to SAR. Mandatory for F-road days.", url:"https://www.112.is"},
      {text:"Gaia GPS — download Iceland offline maps", sub:"Essential for Lónsöræfi (Day 9) and Remundargil (Day 5)."},
      {text:"Wikiloc — save Remundargil + Lónsöræfi Hvítserkur routes offline"},
      {text:"Bookmark umferdin.is/en/road/91381 — F207 Laki live status", sub:"Check morning of Day 6 (Jul 5).", url:"https://umferdin.is/en/road/91381"},
      {text:"Bookmark safetravel.is", sub:"Register F88 (Day 12) and F206 (Day 6) before entering.", url:"https://safetravel.is"},
      {text:"Bookmark umferdin.is/en — general road conditions", url:"https://umferdin.is/en"},
      {text:"Bookmark en.vedur.is — Iceland 48hr weather forecast", url:"https://en.vedur.is"},
      {text:"Google Maps — download Iceland offline map pack"},
    ]},
    {section:"Clothing + gear", badge:"gear", items:[
      {text:"Waterproof jacket (taped seams) × each", sub:"Keep in truck cab AT ALL TIMES."},
      {text:"Waterproof trousers × each"},
      {text:"Merino wool base layer top × 3 each"},
      {text:"Merino wool base layer bottom × 2 each"},
      {text:"Warm mid-layer (fleece or down puffy) × each", sub:"Askja/Dreki highlands near freezing even in July."},
      {text:"Warm hat + gloves × each"},
      {text:"Hiking boots (stiff, ankle support, waterproof) × each", sub:"Break in 2+ weeks before departure."},
      {text:"Camp sandals × each"},
      {text:"Dry bags (5L, 10L, 20L) for truck bed", sub:"Everything in truck bed must be waterproofed."},
      {text:"Camp stove + fuel canisters", sub:"Buy gas in Iceland — cannot fly with pressurised canisters."},
      {text:"Cooking pot, pan, utensils, plates, mugs"},
      {text:"Power banks × 2 (20,000mAh+)", sub:"No power at Dreki or any F-road camp."},
      {text:"Sunscreen SPF 50+ × 2 tubes", sub:"Midnight sun UV is real on glaciers and lagoons."},
      {text:"Polarised sunglasses × each", sub:"Essential on the glacier — cuts ice and water glare."},
      {text:"Reusable water bottles × 2 each (1L minimum)"},
      {text:"Quick-dry travel towel × each", sub:"For Viti crater swim, Forest Lagoon, campsite showers."},
      {text:"Personal medications + surplus"},
      {text:"Small padlock for hostel lockers"},
    ]},
    {section:"Vehicle check (on collection at KEF)", badge:"gear", items:[
      {text:"Full-size spare tyre confirmed — not a space-saver", sub:"Insist on this before leaving the lot."},
      {text:"Tyre pressure checked on collection"},
      {text:"F-road insurance confirmed in writing — F88, F206, F207"},
      {text:"Duct tape (large roll) in truck"},
      {text:"Windscreen washer fluid level checked"},
      {text:"Jump cables or compact battery jump starter"},
      {text:"Emergency bivvy bag × 2"},
      {text:"Head torch × 2 + spare batteries"},
      {text:"RTT opens and closes correctly — test before leaving lot"},
      {text:"All existing damage noted on collection form"},
    ]},
    {section:"Day-of reminders", badge:"urgent", items:[
      {text:"Day 4 (Jul 3): Skógar river trail HARD STOP at 10:15am", sub:"Set a phone alarm. The Sterna bus cannot be missed."},
      {text:"Day 6 (Jul 5): check umferdin.is/en/road/91381 for F206/F207 status", sub:"If CLOSED → drive direct to Skaftafell. Day 7 unaffected."},
      {text:"Day 12 (Jul 11): fill fuel MAX + 20L jerry can at Mývatn before F88", sub:"Non-negotiable. Zero fuel on F88."},
      {text:"Day 12 (Jul 11): register F88 route at safetravel.is before entering"},
      {text:"Day 15 (Jul 14): leave Snæfellsnes glacier tip by 11:15am", sub:"Hard deadline. 4pm KEF departure."},
      {text:"Day 15 (Jul 14): fill fuel at Orkan before rental return"},
      {text:"Every F-road day: walk every river crossing before driving"},
    ]},
    {section:"Emergency contacts", badge:"info", items:[
      {text:"Icelandic emergency — 112", sub:"112 Iceland app sends GPS automatically."},
      {text:"Road conditions + SAR — 1777 (24hrs)"},
      {text:"Your rental company emergency number", sub:"Save in phone AND write on paper."},
      {text:"Arctic Adventures — adventures.is", sub:"Day 7 Glacier Xtreme operator."},
      {text:"Forest Lagoon — forestlagoon.is · +354 xxx xxxx", sub:"Day 13 geothermal spa."},
      {text:"Travel insurance 24hr helpline", sub:"Save number in phone AND on paper."},
      {text:"KEF Airport — +354 425 6000"},
    ]},
  ],
};
