// Iceland Ring Road 2026 — Complete Trip Data
// 16 days: Jun 30 – Jul 14 (fly home 4pm Jul 14)
// Excursions: Glacier Xtreme, Canyoning, Sterna bus, Drangey island, Forest Lagoon
// Removed: Katla ice cave, whale watching, both puffin tours, Earth Lagoon (closed)
// Adjusted: Days 1-5 split/expanded, Day 13 Forest Lagoon, Day 14 Drangey boat tour

const FROAD_DATA = {
  F206_Laki:{
    name:"F206/F207 — Lakagígar (Laki Craters)",
    liveUrl:"https://umferdin.is/en/road/91381",
    historical:{2021:"25 Jun",2022:"1 Jul",2023:"12 Jun",2024:"18 Jun",2025:"12 Jun"},
    earliest:"12 June", latest:"1 July", average:"20 June",
    risk:"medium", tripDay:6, tripDate:"Jul 5",
    note:"Average opening Jun 20 — likely open Jul 5 but not guaranteed. In 2022 it didn't open until July 1 (4 days before your visit). Verify at umferdin.is/en/road/91381 every morning the week before. If closed: proceed direct to Skaftafell — Day 7 is unaffected."
  },
  F208_Landmannalaugar:{
    name:"F208 north — Sigalda to Landmannalaugar",
    liveUrl:"https://umferdin.is/en",
    historical:{2021:"12 Jun",2022:"23 Jun",2023:"1 Jun",2024:"12 Jun",2025:"23 May"},
    earliest:"23 May", latest:"23 June", average:"2 June",
    risk:"low", tripDay:3, tripDate:"Jul 2",
    note:"Average opening June 2. Almost certainly open for Jul 2. Lowest risk F-road on the trip. No river crossings on the northern F208 approach from Hrauneyjar."
  },
  F88_Askja:{
    name:"F88 — Öskjuvegur (Askja / Dreki hut)",
    liveUrl:"https://umferdin.is/en",
    historical:{note:"Not in official IRCA table — typically opens late June to early July."},
    earliest:"late June", latest:"early July", average:"late June",
    risk:"low", tripDay:12, tripDate:"Jul 11",
    note:"F88 typically opens late June. By Jul 11 it has been open roughly 2–3 weeks in most years. Still check road.is and register at safetravel.is the morning of departure."
  }
};

const TRIP_DATA = {
  days:[
    // ── DAY 1 ─────────────────────────────────────────────────────────────────
    {
      num:1, date:"Jun 30", dow:"Monday",
      title:"Arrive Reykjavík",
      sleep:"hostel", accommodation:"Loft HI Hostel, Bankastræti 7, Reykjavík",
      tags:["hostel"], lat:64.1466, lng:-21.9426,
      summary:"Land 10:30am KEF. Collect truck — confirm F-road insurance in writing. Big Bónus grocery shop. Reykjavík on foot: Hallgrímskirkja, Sun Voyager, Harpa, hot dogs. Perlan rooftop at midnight sun.",
      distance:"~60km", drive:"45 min KEF to Reykjavík",
      schedule:[
        {time:"10:30am", desc:"Land at Keflavík International Airport (KEF)", note:"Allow 35–40 min for baggage and customs. Passport control queues are long in peak July."},
        {time:"11:15am", desc:"Pick up 4x4 truck at rental company", note:"CRITICAL: Confirm in writing that F88, F206, and F207 are covered by your F-road insurance. Insist on a full-size spare tyre — not a space-saver. Practice opening and closing the rooftop tent before leaving the lot. Note all existing damage on the collection form."},
        {time:"12:00pm", desc:"Drive to Reykjavík — stop at Bónus supermarket (Laugavegur 59) for the main trip grocery shop", note:"Buy for 3–4 days on the road: oats, eggs, pasta, rice, bread, hard cheese, cured meats, peanut butter, nuts, Skyr, instant coffee, cooking oil, salt. Budget ~$60 for 2 people. Buy camp gas canisters here — you cannot fly with them and Bónus is cheapest."},
        {time:"1:30pm", desc:"Check in to Loft HI Hostel, Bankastræti 7", note:"Drop bags. Kitchen available. Everything in Reykjavík is walkable from here."},
        {time:"2:30pm", desc:"Hallgrímskirkja church — climb the tower (~$11pp)", note:"Best panorama of Reykjavík. The basalt column architecture was inspired by Svartifoss waterfall — which you'll see Day 7. Notice the Leif Erikson statue outside."},
        {time:"3:30pm", desc:"Sun Voyager sculpture → Harpa concert hall waterfront walk", note:"Free. 25 min coastal walk. Harpa's facade was designed by Olafur Eliasson — walk inside. Sun Voyager is Iceland's most photographed sculpture."},
        {time:"5:00pm", desc:"Bæjarins Beztu Pylsur — hot dog stand, Tryggvagata 1", note:"Order 'eina með öllu' — ketchup, sweet mustard, remoulade, raw and fried onions. ~$4. Bill Clinton ate here. Queue moves fast."},
        {time:"6:30pm", desc:"Laugavegur street walk + any last shopping", note:"Kronán is open late for anything missed at Bónus."},
        {time:"8:00pm", desc:"Perlan free rooftop viewing deck — 360° city panorama", note:"Free (museum inside charges). 2km south of centre — drive or bus 18."},
        {time:"10:00pm", desc:"Pack tomorrow's kit in truck cab. Alarm 7:00am.", note:"Waterproofs, snacks, water in cab — not truck bed. Day 2 is a proper drive + hike day."},
      ],
      hikes:[], excursions:[],
      tips:[
        "Iceland tap water is safe, cold, and excellent everywhere. Never buy bottled water — it's wasteful and unnecessary.",
        "Midnight sun starts tonight. The sun barely dips below the horizon in late June. Bring a sleep mask or RTT blackout liner — you will need it.",
        "Orkan petrol stations are cheapest in Iceland — about 5% less than N1 and Shell. Download the Orkan app for a further 3–5% discount per litre.",
        "Iceland is essentially cashless. Pay by contactless card everywhere — ATM withdrawal fees add up unnecessarily.",
      ],
      warnings:[],
      costs:{accommodation:45, food:65, activities:11}
    },
    // ── DAY 2 ─────────────────────────────────────────────────────────────────
    {
      num:2, date:"Jul 1", dow:"Tuesday",
      title:"Háifoss Gorge + Seljalandsfoss + Midgard",
      sleep:"hostel", accommodation:"Midgard Base Camp, Hvolsvöllur",
      tags:["hostel","hike"], lat:63.5309, lng:-20.2309,
      summary:"Route 332 to Háifoss — 122m waterfall, gorge descent to the base. Seljalandsfoss walk-behind waterfall + hidden Gljúfrabúi cave waterfall. Relaxed arrival at Midgard Base Camp. Early night before the Landmannalaugar day.",
      distance:"~220km", drive:"~3 hrs total driving",
      schedule:[
        {time:"7:30am", desc:"Depart Reykjavík east on Ring Road (Route 1)"},
        {time:"8:45am", desc:"Turn north on Route 32 then 327/332 to Háifoss", note:"Rough gravel track. High clearance required — drive slowly. Parking ~$8 via Parka.is."},
        {time:"9:15am", desc:"Háifoss rim viewpoint — 15 min", note:"Both Háifoss (122m) and Granni waterfall visible side-by-side from the canyon edge. The canyon drops 100m+ straight down."},
        {time:"9:30am", desc:"Háifoss gorge descent hike", note:"Allow 1.5–2 hrs. Scramble into the canyon to the base of both waterfalls. Almost nobody does this. Waterproofs essential — you get soaked."},
        {time:"11:30am", desc:"Drive back to Ring Road south, then east toward Seljalandsfoss"},
        {time:"1:00pm", desc:"Seljalandsfoss — walk behind the waterfall curtain", note:"Parking ~$8. The path loops behind the waterfall — get completely surrounded by falling water. Allow 20 min."},
        {time:"1:30pm", desc:"Gljúfrabúi hidden cave waterfall — 5 min north of Seljalandsfoss", note:"FREE. Follow the cliff north — a narrow gorge opens into a cave with a waterfall dropping inside. Enter by stepping across a stream. Far fewer people know about this than Seljalandsfoss. Waterproofs useful."},
        {time:"2:30pm", desc:"Drive east to Hvolsvöllur → Midgard Base Camp (~25 min)"},
        {time:"3:30pm", desc:"Check in. Shower. Rest. Lay out kit for tomorrow.", note:"Midgard Base Camp has excellent kitchen and knowledgeable staff. One meal out is worth it here."},
        {time:"6:00pm", desc:"Dinner at Midgard restaurant or cook in hostel kitchen"},
        {time:"9:00pm", desc:"Early night. Alarm 8:00am tomorrow."},
      ],
      hikes:[
        {name:"Háifoss Gorge Descent", distance:"4km RT", difficulty:"Moderate", gain:"300m into canyon", time:"1.5–2 hrs",
        desc:"Háifoss's best-kept secret. From the rim, follow the canyon edge north until the scramble path appears — steep grass and scree down to the stream bed and the base of both Háifoss (122m, Iceland's 4th highest) and Granni (90m) falls side-by-side. Mist-soaked and extraordinary. Stranger Things Season 8 filmed on the rim above. Almost no tourists make this descent."},
      ],
      excursions:[],
      tips:[
        "Gljúfrabúi is one of Iceland's best-kept secrets. Enter by stepping on stones across the stream and squeezing through a narrow gorge — the waterfall drops inside a domed cave. Wear waterproofs.",
        "Midgard Base Camp staff are Ring Road veterans. Ask them about F208 north conditions and Þórsmörk bus timing over dinner.",
      ],
      warnings:[],
      costs:{accommodation:50, food:30, activities:0}
    },
    // ── DAY 3 ─────────────────────────────────────────────────────────────────
    {
      num:3, date:"Jul 2", dow:"Wednesday",
      title:"Landmannalaugar — Rainbow Mountains",
      sleep:"camp", accommodation:"Landmannalaugar campsite (NOT on Camping Card, ~$25pp)",
      tags:["camp","hike","froad"], lat:63.9906, lng:-19.0607,
      froad:{id:"F208_Landmannalaugar", risk:"low", note:"Average opening Jun 2. Almost certainly open. No river crossings on F208 north."},
      summary:"Full day dedicated to Landmannalaugar. F208 north (no river crossings). Three hikes in the rainbow rhyolite mountains. Natural hot spring soak under the midnight sun.",
      distance:"~180km", drive:"~2.5 hrs total",
      schedule:[
        {time:"8:00am", desc:"Depart Midgard Base Camp — drive east on Ring Road then north on Route 26"},
        {time:"9:30am", desc:"Enter F208 north at Hrauneyjar junction — drive 45 min to Landmannalaugar", note:"Clearly signed off Route 26. Zero river crossings on this route — safe for your rental. The F-road begins immediately after the junction."},
        {time:"10:15am", desc:"Arrive Landmannalaugar. Pay campsite fee and set up tent — pitches fill up.", note:"~$25pp. NOT on Camping Card. Confirm parking reservation at fi.is if arriving 9am–4pm (2026 rule)."},
        {time:"11:00am", desc:"Laugahraun lava field walk — easy 30 min warm-up", note:"Through the 1477 eruption lava bordering the campsite. Obsidian glass shards visible on the ground."},
        {time:"11:30am", desc:"Brennisteinsalda rainbow volcano loop hike"},
        {time:"1:30pm", desc:"Lunch at camp — cook on stove"},
        {time:"2:30pm", desc:"Bláhnúkur Blue Peak summit hike — best viewpoint in Landmannalaugar"},
        {time:"5:30pm", desc:"Return from summit. Eat. Rest."},
        {time:"7:00pm", desc:"Natural hot spring soak at the hut", note:"~38–40°C. Free with campsite. Change in hut changing rooms. Soak as long as you like."},
        {time:"9:00pm", desc:"Cook dinner. Download Gaia GPS trails for tomorrow (Stakkholtsgjá, Remundargil).", note:"Minimal signal at Landmannalaugar — download everything you need tonight."},
        {time:"Late", desc:"Midnight sun walk through the rhyolite valley — 11pm–1am the colours are extraordinary."},
      ],
      hikes:[
        {name:"Brennisteinsalda Loop", distance:"4km", difficulty:"Moderate", gain:"200m", time:"1.5–2 hrs",
        desc:"Circuit around the steam-venting rainbow volcano ('the sulphur wave'). Red, green, yellow, white mineral bands on the flanks. Fumaroles hiss from vents alongside the trail. Summit gives sweeping views into the valley and over the vast lava field. Marked trail — poles useful on rough sections."},
        {name:"Bláhnúkur Blue Peak", distance:"6km RT", difficulty:"Moderate–Challenging", gain:"350m", time:"2.5 hrs",
        desc:"Landmannalaugar's finest viewpoint at 943m. In every direction: red volcanoes, green obsidian lava, white snow patches, blue distant glaciers. Upper section is steep and loose — go slowly. Best in evening light when the crowds thin. Genuinely one of Iceland's great hikes."},
      ],
      excursions:[],
      tips:[
        "Don't rush Bláhnúkur — the upper loose section needs slow careful footwork. Poles make a real difference.",
        "The hot spring soak in the evening after two big hikes is one of the best moments of the trip. Your legs will thank you.",
        "Hut café sells food but it is overpriced. Cook your own.",
        "This day has no pressure or moving parts. Enjoy the pace.",
      ],
      warnings:[
        "F208 NORTH from Hrauneyjar only. Do NOT use F225 southern approach — river crossings void rental insurance.",
        "Road 332 to Háifoss (yesterday) has sharp rocks. Already done — just a reminder to drive carefully on all gravel tracks.",
      ],
      costs:{accommodation:25, food:22, parking:10}
    },
    // ── DAY 4 ─────────────────────────────────────────────────────────────────
    {
      num:4, date:"Jul 3", dow:"Thursday",
      title:"Skógafoss + Þórsmörk Bus + Þakgil Canyon Camp",
      sleep:"camp", accommodation:"Þakgil Canyon Campsite (+354 893 4889 · thakgil.is)",
      tags:["camp","hike","excursion"], lat:63.5309, lng:-18.8887,
      summary:"Exit Landmannalaugar early. Skógafoss staircase and upstream river trail (hard stop 10:15am). Sterna bus to Þórsmörk — Stakkholtsgjá cave canyon is the priority hike. Camp inside Þakgil canyon with cave dining room.",
      distance:"~130km driving + bus",
      schedule:[
        {time:"7:30am", desc:"Exit Landmannalaugar via F208 south to Ring Road (~45 min)"},
        {time:"9:00am", desc:"Skógafoss — climb the 370-step staircase", note:"Parking ~$8. At the top look right (north) for the river trail path."},
        {time:"9:30am", desc:"Skógar River Trail — hike upstream", note:"HARD STOP AT 10:15am. Set an alarm. Do not let the trail absorb you — the bus cannot be missed. Push to the 5th or 6th waterfall."},
        {time:"10:15am", desc:"HARD STOP — turn around regardless of where you are on the trail."},
        {time:"10:45am", desc:"Return to parking. Drive 20 min west to Hvolsvöllur."},
        {time:"11:15am", desc:"Leave truck at Midgard Base Camp parking (free, notify reception)"},
        {time:"12:00pm", desc:"Board Sterna bus — Þórsmörk (~$44pp return)", note:"Confirm exact departure time when booking sterna.is. Bus crosses F249 river — voids rental insurance if driven. Sit right side for best river crossing views."},
        {time:"1:30pm", desc:"Arrive Þórsmörk (Volcano Huts). Begin Stakkholtsgjá canyon immediately."},
        {time:"3:30pm", desc:"Return from Stakkholtsgjá. Assess time and energy.", note:"If legs are good and time allows: start Valahnúkur summit (2.5 hrs). If not: sit in the valley and watch the glaciers — that's a perfectly full afternoon."},
        {time:"5:30pm", desc:"RETURN STERNA BUS — HARD DEADLINE", note:"Set alarm 45 min before departure. There is no later bus. Pick up truck from Midgard."},
        {time:"6:30pm", desc:"Drive east on Ring Road ~10 min, turn south on Road 214"},
        {time:"7:15pm", desc:"45-min drive up Road 214 to Þakgil", note:"NOT an F-road. Steep and unpaved but manageable. Canyon walls close in dramatically on approach."},
        {time:"8:00pm", desc:"Arrive Þakgil. Check in. Eat at cave café (Búar).", note:"Cave dining room built into the canyon cliff. Eat there tonight. Canyon walls glow gold 11pm–1am."},
      ],
      hikes:[
        {name:"Skógar River Trail Upstream", distance:"Hard stop at 10:15am", difficulty:"Moderate", gain:"300m+", time:"~45 min upstream",
        desc:"Follow the Skóga river past 10+ named waterfalls. Each more dramatic and crowd-free than the last. The trail ends at the Fimmvörðuháls volcanic pass — you won't get there today, but the first 45 minutes is extraordinary. Hard stop at 10:15am regardless of where you are."},
        {name:"Stakkholtsgjá Cave Canyon", distance:"5km RT", difficulty:"Moderate", gain:"100m", time:"2 hrs",
        desc:"The priority Þórsmörk hike. From Volcano Huts the marked path enters a narrowing slot canyon — walls close in, light reduces to a strip above, river echoes in the rock. Ends at a natural cave with a waterfall dropping from the ceiling into a pool inside. Twenty One Pilots filmed 'Jumpsuit' here. Check flood conditions on the bus."},
        {name:"Valahnúkur Summit (if time + energy)", distance:"5km", difficulty:"Moderate", gain:"300m", time:"2.5 hrs",
        desc:"Optional — only if Stakkholtsgjá is done and legs are willing. Best panorama of the valley: Eyjafjallajökull, Mýrdalsjökull, Tindfjallajökull on three sides. If you only do Stakkholtsgjá, that's a complete and excellent afternoon."},
      ],
      excursions:[
        {name:"Sterna Highland Bus — Þórsmörk Return", operator:"Sterna (sterna.is)", price:"~$44pp", duration:"Transport only",
        url:"https://www.sterna.is",
        desc:"F249 river crossings into Þórsmörk void rental car insurance on almost all policies. The Sterna bus crosses safely using purpose-modified coaches. Without this bus, Þórsmörk is inaccessible on your policy. Book at least 2 weeks ahead in July. Leave truck at Midgard Base Camp, Hvolsvöllur — free, notify reception."},
      ],
      tips:[
        "The 10:15am hard stop on the Skógar river trail is the most important scheduling decision of the day. Set a phone alarm the moment you start hiking.",
        "Stakkholtsgjá is the better and more unique of the two Þórsmörk hikes. If you only do one, do this one.",
        "Þakgil cave café closes ~9:30pm. Arrive hungry.",
      ],
      warnings:[
        "DO NOT miss the return Sterna bus. There is no other way out of Þórsmörk. Set alarm 45 min before departure.",
        "DO NOT attempt to drive F249 to Þórsmörk. The river crossing voids your rental insurance.",
      ],
      costs:{accommodation:24, food:22, activities:44}
    },
    // ── DAY 5 ─────────────────────────────────────────────────────────────────
    {
      num:5, date:"Jul 4", dow:"Friday",
      title:"Þakgil Morning Hike + Dyrhólaey Puffins + Vík",
      sleep:"hostel", accommodation:"Vík HI Hostel (hostel.is)",
      tags:["hostel","hike"], lat:63.4190, lng:-19.0055,
      summary:"Early Remundargil canyon loop from camp with Katla glacier views. Relaxed south coast afternoon: Dyrhólaey puffin cliffs (peak July nesting), Reynisfjara black sand beach. Easy arrival at Vík HI Hostel.",
      distance:"~80km",
      schedule:[
        {time:"7:00am", desc:"Remundargil canyon loop from Þakgil camp", note:"Trail map at campsite reception. Canyon in morning light is extraordinary. Early start while other campers sleep."},
        {time:"10:30am", desc:"Return to camp. Breakfast at cave café (Búar)."},
        {time:"11:30am", desc:"Pack camp, load truck, drive down Road 214 (~45 min)"},
        {time:"1:00pm", desc:"Drive to Dyrhólaey — upper lighthouse viewpoint", note:"Go to UPPER parking (lighthouse level). Look DOWN at the cliff face — puffins nest in burrows directly below, thousands of them. July = peak nesting. Parking ~$8."},
        {time:"2:00pm", desc:"Dyrhólaey sea arch — walk to the arch viewpoint"},
        {time:"3:00pm", desc:"Reynisfjara black sand beach", note:"Basalt column cave (Hálsanefshellir) accessible at low tide. See warnings."},
        {time:"4:30pm", desc:"Vík town. Check in HI Hostel. Cook dinner.", note:"Krónan supermarket in Vík for top-up supplies. Last proper shop before Skaftafell."},
        {time:"Evening", desc:"Walk up to Víkurkirkja (Vík church) on the hill — views over black sand and Reynisdrangar sea stacks.", note:"Free. 20 min walk from town. One of the better viewpoints in south Iceland."},
      ],
      hikes:[
        {name:"Remundargil Canyon Loop", distance:"12.5km", difficulty:"Moderate", gain:"250m", time:"3–4 hrs",
        desc:"From Þakgil camp, the loop follows canyon rims above the Remundargil gorge, descends into the interior, returns via the valley floor. Ridgeline gives views of Mýrdalsjökull glacier (above Katla volcano) to the north. Parts unmarked — download Wikiloc or Gaia GPS route. Bring water and snacks, nothing on route."},
      ],
      excursions:[],
      tips:[
        "Dyrhólaey puffins: upper lighthouse viewpoint, look DOWN at the cliff face. Give it 30 quiet minutes — the colony is enormous.",
        "Víkurkirkja church on the hill above Vík: the views from here are underrated and the church itself is photogenic. Worth the 20-min walk.",
      ],
      warnings:[
        "REYNISFJARA: never turn your back on the ocean. Sneaker waves kill people here every year with no warning. Stay well above the high tide line at all times.",
      ],
      costs:{accommodation:45, food:20, activities:0}
    },
    // ── DAY 6 ─────────────────────────────────────────────────────────────────
    {
      num:6, date:"Jul 5", dow:"Saturday",
      title:"Fjáðrárgljúfur Canyon + Laki Craters F206/F207",
      sleep:"camp", accommodation:"Blágil Hut Campsite (+354 487 4840)",
      tags:["camp","hike","froad"], lat:64.0707, lng:-18.2378,
      froad:{id:"F206_Laki", risk:"medium", note:"Average opening Jun 20. Likely open Jul 5 — check umferdin.is/en/road/91381 every morning this week."},
      summary:"Check F207 status first. Fjáðrárgljúfur glacial canyon. F206/F207 Laki crater field loop — 130 craters from the 1783 eruption that killed 25% of Iceland's population. Mt. Laki summit. Sleep at Blágil highland hut.",
      distance:"~200km including F-road loop",
      schedule:[
        {time:"6:30am", desc:"CHECK umferdin.is/en/road/91381 for F207 status", note:"If CLOSED: skip to Skaftafell directly. Day 7 Glacier Xtreme is completely unaffected."},
        {time:"6:45am", desc:"Register route at safetravel.is before entering F206"},
        {time:"7:00am", desc:"Depart Vík east on Ring Road"},
        {time:"7:45am", desc:"Fjáðrárgljúfur canyon — Route 206 turnoff near Kirkjubæjarklaustur", note:"Park at signed lot. Short flat walk to canyon rim. 100m-deep canyon carved by glacial meltwater. GoT Season 8. Parking ~$8."},
        {time:"8:00am", desc:"Fjáðrárgljúfur rim walk — 30–60 min"},
        {time:"8:45am", desc:"Fill fuel to MAXIMUM at Kirkjubæjarklaustur petrol station", note:"MANDATORY — zero fuel inside the F206/F207 loop."},
        {time:"9:00am", desc:"Turn north on F206 (Lakavegur)", note:"50km to Laki, ~2 hrs. Multiple river crossings. Walk every crossing before driving."},
        {time:"10:30am", desc:"Fagrifoss waterfall — short stop on F206 (free)"},
        {time:"11:30am", desc:"Arrive Laki crater ranger hut and trailhead"},
        {time:"12:00pm", desc:"Mt. Laki summit hike"},
        {time:"1:30pm", desc:"Visitor Trail through crater interior"},
        {time:"3:30pm", desc:"Drive F207 loop south"},
        {time:"5:30pm", desc:"Blágil hut campsite", note:"Call ahead: +354 487 4840. ~$15pp. NOT on Camping Card. Kitchen, toilets, showers."},
        {time:"Evening", desc:"Walk the highland plateau under the midnight sun. Total isolation."},
      ],
      hikes:[
        {name:"Mt. Laki Summit", distance:"3.5km RT", difficulty:"Moderate", gain:"200m", time:"1–1.5 hrs",
        desc:"From the ranger hut, the marked trail climbs to the summit of Mt. Laki at the centre of the 25km volcanic fissure. From the top: the entire Lakagígar crater row stretches in both directions — 130 craters in a line. The 1783 eruption was one of the most catastrophic in human history — killed 25% of Iceland's population, caused European famines, and contributed to conditions that sparked the French Revolution."},
        {name:"Visitor Trail — Crater Interior", distance:"2km loop", difficulty:"Easy", gain:"50m", time:"45 min",
        desc:"Walk directly into a crater and through the eruption fissure. 240-year-old lava covered in vivid bright green moss. The scale and absolute silence inside the crater field are staggering. Pick up the trail map at the ranger hut."},
      ],
      excursions:[],
      tips:[
        "Read about the 1783 Lakagígar eruption before visiting — the historical context transforms the experience from 'impressive volcanic landscape' to 'genuinely humbling'.",
        "Fagrifoss waterfall on F206 is a 10-min stop that most people skip. Don't — it's beautiful.",
        "Sleeping at Blágil in the highland with midnight sun is one of the atmospheric highlights of the trip.",
      ],
      warnings:[
        "CRITICAL: Check umferdin.is/en/road/91381 before departing Vík. If F206/F207 closed → drive to Skaftafell directly.",
        "Walk every river crossing before driving — never rush a ford. No mobile signal inside the loop.",
        "Register at safetravel.is before entering F206. Zero fuel inside the loop.",
      ],
      costs:{accommodation:15, food:20, fuel:35}
    },
    // ── DAY 7 ─────────────────────────────────────────────────────────────────
    {
      num:7, date:"Jul 6", dow:"Sunday",
      title:"Glacier Xtreme Ice Climbing + Svartifoss",
      sleep:"camp", accommodation:"Skaftafell NP campsite (Camping Card)",
      tags:["camp","hike","excursion"], lat:64.0163, lng:-16.9681,
      summary:"Drive from Blágil to Skaftafell. Glacier Xtreme — 8.5 hours total: ice axe climbing, crevasse rappelling on Falljökull. Svartifoss basalt column waterfall at sunset. Camp Skaftafell.",
      distance:"~80km",
      schedule:[
        {time:"8:00am", desc:"Drive Blágil → Ring Road → east to Skaftafell (~1 hr)"},
        {time:"9:00am", desc:"Arrive Skaftafell. Find Arctic Adventures booking hut in car park.", note:"Parking ~$4. Wooden hut with Arctic Adventures logo at car park entrance."},
        {time:"9:00am", desc:"Glacier Xtreme check-in + gear fitting + safety briefing", note:"PRE-BOOKED at adventures.is ~$242pp. Allow 1 full hour: medical declaration, ice-climbing boot fitting (EU 36–50), crampon fitting, harness, helmet, briefing."},
        {time:"10:00am", desc:"Transport to Falljökull glacier base (20 min, included in tour)"},
        {time:"10:30am", desc:"Glacier Xtreme begins — 7 hours on Falljökull glacier"},
        {time:"5:30pm", desc:"Return transport to Skaftafell. Gear return. Rest and eat."},
        {time:"7:30pm", desc:"Svartifoss waterfall trail — easy 2 hrs, 3.5km RT", note:"Best in evening golden light. Trailhead at Skaftafell visitor centre."},
        {time:"9:30pm", desc:"Set up camp at Skaftafell. Hot showers. Laundry.", note:"Camping Card accepted. One of the best-equipped campsites on the Ring Road."},
        {time:"Late", desc:"Walk 15 min to Skaftafellsjökull glacier lagoon (free) — ice calves into the lagoon, audible at night."},
      ],
      hikes:[
        {name:"Glacier Xtreme on Falljökull (Vatnajökull)", distance:"~8km on glacier", difficulty:"Challenging", gain:"350–400m", time:"7 hrs (8.5 total with check-in)",
        desc:"Falljökull — 'Falling Glacier' — is a Vatnajökull outlet glacier named for the dramatic icefall on its upper section. You hike across the glacier surface past crevasses, moulins, and seracs to the blue ice wall where the climbing begins. Your guide selects the best wall or crevasse for conditions. You learn twin ice axe technique — the swing, the kick, the balance — then climb a vertical face of blue glacial ice. Maximum 6 people per guide. All gear provided: specialized ice-climbing boots, crampons, twin axes, harness, helmet. Bring lunch and water — glacier meltwater is drinkable directly. Most physically demanding day of the trip."},
        {name:"Svartifoss — the Black Waterfall", distance:"3.5km RT", difficulty:"Easy–Moderate", gain:"120m", time:"1.5–2 hrs",
        desc:"Drops over a curtain of dark hexagonal basalt columns — the same geological formation that inspired Hallgrímskirkja church's tower in Reykjavík. The contrast of white water against black columns is striking, especially in evening light. The marked trail passes two smaller viewpoint falls before the main drop."},
      ],
      excursions:[
        {name:"Glacier Xtreme Ice Climbing — Falljökull", operator:"Arctic Adventures (adventures.is)", price:"~$242pp", duration:"7 hrs on glacier / 8.5 hrs total",
        url:"https://adventures.is/iceland/day-tours/glacier-tours/glacier-tours-on-vatnajokull/glacier-xtreme-and-ice-climbing/",
        desc:"BOOK NOW — max 6 per group, July dates sell out within days of opening. Medical declaration required. Not suitable for back problems, heart conditions, pregnancy. Cancellation: 48-hour notice. Bring: warm merino base layer, waterproof jacket and trousers, sunglasses, lunch, 1.5L water, waterproof phone case. Ice-climbing boots provided — warmer and more rigid than hiking boots."},
      ],
      tips:[
        "Big dinner and good sleep tonight — 7 hours on a glacier is the most demanding day of the trip.",
        "Skaftafell campsite has laundry — use it after 6 days on the road.",
        "Svartifoss is best in the evening when crowds have gone and light is golden. Timing after the glacier is perfect.",
      ],
      warnings:["BOOK GLACIER XTREME NOW — the single most in-demand guided glacier activity in Iceland."],
      costs:{accommodation:16, food:20, activities:242}
    },
    // ── DAY 8 ─────────────────────────────────────────────────────────────────
    {
      num:8, date:"Jul 7", dow:"Monday",
      title:"Diamond Beach + Canyoning Under Vatnajökull + Höfn",
      sleep:"hostel", accommodation:"Höfn HI Hostel (hostel.is)",
      tags:["hostel","excursion"], lat:64.2621, lng:-15.2124,
      summary:"Diamond Beach ice chunks on black sand. Half-day canyoning under Vatnajökull — Iceland's only canyoning operator. Höfn hostel. Langoustine dinner.",
      distance:"~110km",
      schedule:[
        {time:"8:30am", desc:"Drive east from Skaftafell to Jökulsárlón / Diamond Beach (~45 min)"},
        {time:"9:15am", desc:"Diamond Beach (Breiðamerkursandur) — 30 min", note:"FREE. Pull off Ring Road at the Jökulsárlón signs on the east/seaward side. Walk the beach where ice chunks from the glacier lagoon wash up on black sand. Some blocks are car-sized and translucent blue. Glacier lagoon is just across the road — enormous icebergs visible from the bridge."},
        {time:"10:00am", desc:"Continue east toward Haukafell Camp (Ice Guardians meetpoint, 35 min west of Höfn)", note:"Haukafell Campsite, Hornafjörður. Look for Ice Guardians signs. Phone: +354 898 2277."},
        {time:"10:30am", desc:"Ice Guardians check-in — wetsuit + harness fitting + safety briefing (30–40 min)", note:"Bring: swimsuit or synthetic base layer (NO cotton), towel, dry change of clothes. Everything else provided."},
        {time:"11:00am", desc:"Half-day canyoning under Vatnajökull — 4–5 hours"},
        {time:"4:00pm", desc:"End of canyoning. Hot drinks included. Change and warm up."},
        {time:"5:00pm", desc:"Drive east to Höfn (~35 min)"},
        {time:"5:30pm", desc:"Check in Höfn HI Hostel"},
        {time:"7:00pm", desc:"Langoustine dinner — Höfn is Iceland's langoustine capital", note:"Pakkhús at the harbour is best (~$30–35pp). Even the Nettó supermarket sells fresh langoustite tails cheaply for self-catering."},
        {time:"Late", desc:"Vatnajökull glow from hostel terrace — ice cap turns pale gold at midnight on clear evenings."},
      ],
      hikes:[],
      excursions:[
        {name:"Half-Day Canyoning Under Vatnajökull", operator:"Ice Guardians (ice-guardians.com)", price:"~$278pp (34,900 ISK)", duration:"4–5 hours",
        url:"https://ice-guardians.com/tour/half-day-canyoning-under-vatnajokull/",
        desc:"Iceland's only canyoning operator — this experience exists nowhere else in the country. Glacial meltwater from Vatnajökull has carved a canyon system directly below the ice cap. Walk through birch forest before descending into the canyon where you abseil down waterfalls, jump into crystal pools, and slide down natural rock chutes. 5mm wetsuit, helmet, harness, neoprene boots provided. Guide ratio: 6:2. Minimum: swim 20m unaided, walk 5km on uneven terrain. Cancellation: 100% fee within 48 hours."},
      ],
      tips:[
        "Pack dry clothes in a separate bag and leave in the truck. The moment the wetsuit comes off you want warm dry layers.",
        "Höfn Nettó supermarket: buy supplies for the East Fjords stretch. Next good shop is Egilsstaðir.",
        "Langoustine: even if self-catering the whole trip, eat properly here once. It's genuinely exceptional.",
      ],
      warnings:[
        "No cotton under the wetsuit — synthetic or merino base layer only. Cotton traps cold water against skin.",
        "Not suitable: back problems, heart conditions, pregnancy. Declare medical conditions to guides.",
      ],
      costs:{accommodation:45, food:50, activities:278}
    },
    // ── DAY 9 ─────────────────────────────────────────────────────────────────
    {
      num:9, date:"Jul 8", dow:"Tuesday",
      title:"East Fjords Coast + Stafafell + Lónsöræfi Canyon",
      sleep:"camp", accommodation:"Stafafell Nature Park (+354 699 6684)",
      tags:["camp","hike"], lat:64.4197, lng:-14.8439,
      summary:"Scenic East Fjords coastal drive over dramatic passes. Stafafell farm campsite — possibly the most peaceful camp of the trip. Lónsöræfi red rhyolite canyon — Iceland's most overlooked highland, virtually zero visitors.",
      distance:"~180km",
      schedule:[
        {time:"9:00am", desc:"Depart Höfn north on Ring Road — East Fjords coastal drive", note:"Winding road over multiple fjord passes with ocean views. Stop whenever the scenery demands it — no schedule pressure today."},
        {time:"11:30am", desc:"Arrive Stafafell Nature Park. Call ahead: +354 699 6684", note:"Tiny family-run farm campsite in a sheltered valley. You may be the only guests."},
        {time:"12:00pm", desc:"Cook lunch at camp. Rest. Load day pack."},
        {time:"1:30pm", desc:"Begin Lónsöræfi Hvítserkur canyon hike via F985 track"},
        {time:"6:30pm", desc:"Return from canyon. Cook dinner at camp."},
        {time:"Evening", desc:"Total silence, extraordinary rhyolite views. Let the legs recover."},
      ],
      hikes:[
        {name:"Lónsöræfi Hvítserkur Red Rhyolite Canyon", distance:"8–15km", difficulty:"Moderate", gain:"400m", time:"4–5 hrs",
        desc:"Iceland's most overlooked highland area. Jagged rust-red and orange rhyolite peaks rising from a hidden valley. Sees a fraction of the visitors that Landmannalaugar gets, but equally extraordinary — just without the crowds. Access via F985 from Stafafell (mild track, manageable in dry conditions). Trail unmarked in sections — download Gaia GPS beforehand. Water from mountain streams only: bring Sawyer Squeeze filter. Best in evening light when the colours intensify."},
      ],
      excursions:[],
      tips:[
        "Lónsöræfi in evening light (7–9pm) is genuinely special. The rhyolite changes from orange to deep red as the sun drops angle.",
        "Stafafell is the most peaceful camp of the trip. No phone signal. Complete isolation.",
        "This is the cheapest day of the trip — campsite and a hike. Embrace the simplicity.",
      ],
      warnings:[
        "Lónsöræfi trail is partially unmarked. Download Gaia GPS route before leaving Höfn. Bring water filter.",
      ],
      costs:{accommodation:14, food:18}
    },
    // ── DAY 10 ────────────────────────────────────────────────────────────────
    {
      num:10, date:"Jul 9", dow:"Wednesday",
      title:"Stuðlagil Canyon + Seyðisfjörður + Egilsstaðir Resupply",
      sleep:"hostel", accommodation:"East Guesthouse, Egilsstaðir (eastguesthouse.is)",
      tags:["hostel","hike"], lat:65.2590, lng:-14.3952,
      summary:"Stuðlagil basalt column canyon — turquoise river, 30m hexagonal columns, still undervisited internationally. Seyðisfjörður rainbow road and blue church. Major resupply at Egilsstaðir.",
      distance:"~200km",
      schedule:[
        {time:"9:00am", desc:"Depart Stafafell north on Ring Road"},
        {time:"9:30am", desc:"Check upstream weather before committing to Stuðlagil", note:"Heavy rain upstream = white opaque river, not turquoise. Check on phone now. If white, skip and add time at Seyðisfjörður instead."},
        {time:"10:00am", desc:"Turn north on Route 923 to Stuðlagil Canyon (~45 min from Ring Road)"},
        {time:"11:00am", desc:"Stuðlagil Canyon east rim hike — go to EAST car park", note:"The east rim is the iconic viewpoint. 30m basalt columns rising from turquoise river."},
        {time:"2:30pm", desc:"Drive back to Ring Road, north and east over mountain pass to Seyðisfjörður (~1.5 hrs)"},
        {time:"4:00pm", desc:"Seyðisfjörður — rainbow road, blue church, café stop", note:"45–60 min. Rainbow-painted road leads to Bláa Kirkjan blue church. Artists' village. Skaftfell Bistro has excellent food."},
        {time:"5:30pm", desc:"Drive back to Egilsstaðir (~45 min)"},
        {time:"6:15pm", desc:"Check in East Guesthouse. MAJOR RESUPPLY.", note:"Bónus supermarket, Orkan fuel, camp gas canisters. Laundry if possible. Last proper shop until Akureyri."},
      ],
      hikes:[
        {name:"Stuðlagil Canyon East Rim", distance:"4–8km RT", difficulty:"Easy–Moderate", gain:"100m", time:"2–4 hrs",
        desc:"Hexagonal basalt columns rising 30m from a turquoise glacial river. The canyon was entirely underwater until 2009 when a hydroelectric dam upstream dropped the river level, revealing the columns. Go to the EAST car park for the iconic viewpoint. Early morning or evening gives the best turquoise colour — heavy rain upstream turns the river white and opaque. Walk as far as Stuðlafoss waterfall for the best views."},
      ],
      excursions:[],
      tips:[
        "East car park for Stuðlagil — the west side viewpoint is inferior. Don't be fooled by GPS routing to the wrong side.",
        "Seyðisfjörður: the Skaftfell Bistro has genuinely excellent food. The village has an artist community feel and the ferry to mainland Europe departs on Thursdays.",
        "Egilsstaðir resupply is critical. Next reliable supermarket is Akureyri.",
      ],
      warnings:[
        "Check river colour before driving the Route 923 detour — white water after rain means no reward for the detour.",
      ],
      costs:{accommodation:45, food:25}
    },
    // ── DAY 11 ────────────────────────────────────────────────────────────────
    {
      num:11, date:"Jul 10", dow:"Thursday",
      title:"Mývatn — Volcanic Wonderland (All Free)",
      sleep:"camp", accommodation:"Hlíð Campsite, Lake Mývatn (Camping Card)",
      tags:["camp","hike"], lat:65.6495, lng:-16.9187,
      summary:"Goðafoss waterfall. Hverfjall perfectly circular crater rim hike. Dimmuborgir lava tower formations. Grjótagjá Game of Thrones cave hot spring. All free. Head nets mandatory.",
      distance:"~200km from Egilsstaðir",
      schedule:[
        {time:"8:00am", desc:"Depart Egilsstaðir west on Ring Road (~175km, 2.5 hrs)", note:"Buy head nets HERE before leaving if you don't have them. Egilsstaðir is your last reliable shop before Mývatn."},
        {time:"10:00am", desc:"Goðafoss — Waterfall of the Gods (free, 30–45 min)", note:"Right off Ring Road. 12m high, 30m wide. In 1000 AD Iceland voted to adopt Christianity and the lawspeaker threw Norse god idols into these falls."},
        {time:"11:00am", desc:"Hverfjall volcano crater rim hike", note:"Parking ~$8. STAY ON MARKED PATH — tephra is permanently damaged by off-path footsteps."},
        {time:"1:30pm", desc:"Dimmuborgir lava formations (free, 30–90 min)", note:"Take the 'Church' loop for the most dramatic towers and arches."},
        {time:"3:00pm", desc:"Grjótagjá lava cave hot spring (free, 30 min)", note:"The GoT cave (Jon Snow and Ygritte, Season 3). Too hot to swim (~50°C) but the electric blue glow is extraordinary. Bring a small torch."},
        {time:"4:30pm", desc:"Check in Hlíð campsite. HEAD NETS ON IMMEDIATELY.", note:"Camping Card accepted. Do not delay — midges are immediate the moment you exit the truck."},
        {time:"6:00pm", desc:"Cook dinner at camp. Walk lake shore (head nets on)."},
        {time:"Late", desc:"Mývatn lake in midnight light — extraordinary golden reflections."},
      ],
      hikes:[
        {name:"Hverfjall Crater Rim Loop", distance:"3km loop", difficulty:"Moderate", gain:"150m", time:"1.5–2 hrs",
        desc:"Hverfjall is a near-perfect circular tephra cone, 1km wide, formed in a single eruption 2,700 years ago. The rim hike circles the full crater with views into the 1km-wide interior bowl and out over Lake Mývatn. The tephra surface is extremely fragile — permanent damage from a single footstep takes centuries to recover. Marked path only. Best in late-evening light when the lake turns golden."},
      ],
      excursions:[],
      tips:[
        "Head nets at Mývatn are not optional — they are survival gear. Buy before arriving. Midges fly into eyes, ears, mouth constantly without them.",
        "Grjótagjá: both cave chambers are accessible. The electric blue glow from refracted light is the experience. Temperature near 50°C — don't enter the water.",
        "Earth Lagoon Mývatn is closed for 2026 renovation — no paid lagoon today. All free day, which actually takes the pressure off.",
      ],
      warnings:[
        "MIDGES: open the tent zip and they're inside in 10 seconds. Head nets on the moment you step outside at camp.",
        "Stay on marked paths at Hverfjall — off-path footsteps permanently scar the tephra surface.",
      ],
      costs:{accommodation:16, food:18}
    },
    // ── DAY 12 ────────────────────────────────────────────────────────────────
    {
      num:12, date:"Jul 11", dow:"Friday",
      title:"F88 to Askja Caldera + Viti Crater Swim — Dreki Camp",
      sleep:"camp", accommodation:"Dreki Hut Campsite (ffa.is — NOT Camping Card, ~$18pp)",
      tags:["camp","hike","froad"], lat:65.0421, lng:-16.5952,
      froad:{id:"F88_Askja", risk:"low", note:"F88 typically opens late June. By Jul 11 should have been open ~2–3 weeks. Still check road.is morning of."},
      summary:"Fill fuel + 20L jerry can at Mývatn — mandatory. F88 through the world's largest lava field (Ódáðahraun) to Askja. 8km caldera hike. Swim in Viti geothermal crater. Sleep at Dreki under midnight sun.",
      distance:"~120km each way on F88",
      schedule:[
        {time:"7:00am", desc:"FILL FUEL TO ABSOLUTE MAXIMUM at Mývatn + fill 20L jerry can", note:"MANDATORY. F88 is ~120km each way on rough highland road. Your 4x4 burns extra on gravel. Zero fuel available between Mývatn and Ring Road exit."},
        {time:"7:30am", desc:"Register at safetravel.is — F88 to Askja and return"},
        {time:"8:00am", desc:"Enter F88 junction (~20km east of Mývatn on Ring Road)", note:"Allow 2.5 hrs to Dreki. Max 40km/h. The landscape transforms immediately into the dark volcanic Ódáðahraun lava desert."},
        {time:"10:30am", desc:"Arrive Dreki hut. Sign in with rangers. Leave truck.", note:"Rangers track visitors and can advise on trail conditions. Buy snacks and water on site."},
        {time:"11:00am", desc:"Begin Askja caldera hike"},
        {time:"2:30pm", desc:"Viti crater — swim in geothermal crater lake (25–27°C, free)", note:"Path down is steep and slippery — poles essential. Change at truck before hiking, bring towel and dry clothes."},
        {time:"4:00pm", desc:"Return to Dreki. Set up camp."},
        {time:"5:00pm", desc:"Cook big meal — high calories after a demanding day."},
        {time:"Late", desc:"Midnight sun in the highland lava desert — golden light at 1–2am. Set an alarm."},
      ],
      hikes:[
        {name:"Askja Caldera Hike + Viti Crater Swim", distance:"8km RT from Dreki", difficulty:"Moderate", gain:"200m", time:"3–4 hrs",
        desc:"Trail from Dreki crosses ancient lava fields to the Askja caldera rim — Öskjuvatn lake fills the caldera, deep cold blue, formed after the catastrophic 1875 eruption. Continue 15 min to Viti: 1875 explosion crater, 150m wide, containing warm geothermal water at 25–27°C, milky green-blue from minerals. The path down to the water is steep and slippery — poles essential. Swimming inside an active volcanic crater in the highland lava desert is one of the genuinely great experiences of the entire trip."},
      ],
      excursions:[],
      tips:[
        "The F88 drive through Ódáðahraun (world's largest lava field, 3,000 km²) is as remarkable as the caldera itself. Stop and walk out onto the lava — the silence is total.",
        "Viti swim: bring a waterproof bag for your phone — the colours inside the crater are extraordinary and worth photographing.",
        "Midnight at Dreki: the golden light on the lava desert at 1–2am is something else. Set an alarm if you want to catch it.",
      ],
      warnings:[
        "CRITICAL: Fill fuel to maximum + 20L jerry can at Mývatn before entering F88. Zero fuel on this route.",
        "Walk every river crossing before driving — never rush a ford.",
        "Bring warm layers — altitude makes it significantly colder than the Ring Road.",
      ],
      costs:{accommodation:18, food:22, fuel:98}
    },
    // ── DAY 13 ────────────────────────────────────────────────────────────────
    {
      num:13, date:"Jul 12", dow:"Saturday",
      title:"Exit F88 + Akureyri Rest Day + Forest Lagoon",
      sleep:"hostel", accommodation:"Akureyri Guesthouse",
      tags:["hostel","excursion"], lat:65.6814, lng:-18.0898,
      summary:"Drive F88 back to Ring Road. Akureyri: laundry, resupply, botanical garden, reindeer burger. Evening at Forest Lagoon — infinity pools over Eyjafjörður fjord in the birch forest. Full rest day after two highland camps.",
      distance:"~240km",
      schedule:[
        {time:"8:00am", desc:"Exit F88 — same road back, 2.5 hrs to Ring Road"},
        {time:"10:30am", desc:"Fill fuel at first Ring Road station"},
        {time:"12:00pm", desc:"Drive Ring Road west to Akureyri (~90 min)"},
        {time:"1:30pm", desc:"Check in Akureyri Guesthouse. Laundry. Long shower."},
        {time:"3:00pm", desc:"Akureyri Botanical Garden (Lystigarðurinn) — free", note:"World's most northerly botanical garden. Remarkable in full July bloom. 15 min walk from centre."},
        {time:"4:30pm", desc:"Walk Akureyri waterfront and city centre", note:"Heart-shaped traffic lights are the local quirk. Compact and charming."},
        {time:"7:00pm", desc:"Reindeer burger at Akureyri Backpackers restaurant (~$22pp)", note:"Legendary among Ring Road travellers. Large portion."},
        {time:"8:30pm", desc:"Drive to Forest Lagoon, Vaðlaskógur forest (~10 min from centre)", note:"forestlagoon.is. PRE-BOOK. Free shuttle also from Hof cultural centre hourly. Open until midnight in July."},
        {time:"9:00pm", desc:"Forest Lagoon — infinity pools over Eyjafjörður fjord in birch forest", note:"~$44–52pp. Two geothermal infinity pools (37–40°C), Finnish sauna, cold plunge, swim-up bars. Towel rental ~$7."},
        {time:"11:00pm", desc:"Return to guesthouse. Resupply at Bónus if open (check hours)."},
      ],
      hikes:[],
      excursions:[
        {name:"Forest Lagoon Geothermal Spa", operator:"Forest Lagoon (forestlagoon.is)", price:"~$44–52pp (5,990–7,150 ISK)", duration:"2–3 hrs",
        url:"https://www.forestlagoon.is",
        desc:"Opened 2022, the Forest Lagoon was born from a happy accident: workers digging the Vaðlaheiðargöng road tunnel in 2015 struck a natural hot spring beneath the mountain. The complex features two geothermal infinity pools overlooking Eyjafjörður fjord, set among birch and pine trees in Vaðlaskógur forest. The infinity edge drops straight to the fjord view — from the water you look out over the fjord with mountains behind Akureyri. Finnish sauna, cold plunge, two swim-up bars, and a bistro. Far less crowded and more intimate than the Blue Lagoon. An evening slot in the midnight sun here is one of the great North Iceland experiences. Book in advance at forestlagoon.is or email reservations@forestlagoon.is. Towels not included — rent for ~$7 or bring your own."},
      ],
      tips:[
        "Forest Lagoon evening slot: the midnight sun over Eyjafjörður from the infinity pool is extraordinary. Book the 8:30 or 9pm session.",
        "Akureyri is the largest town outside Reykjavík — enjoy the infrastructure. It's the last proper city until you fly home.",
        "This is a full rest day. Don't overschedule — two highland camp nights followed by Drangey tomorrow means rest is valuable.",
      ],
      warnings:[],
      costs:{accommodation:55, food:30, activities:48}
    },
    // ── DAY 14 ────────────────────────────────────────────────────────────────
    {
      num:14, date:"Jul 13", dow:"Sunday",
      title:"Kolugljúfur Canyon + Drangey Island Boat Tour + Snæfellsnes",
      sleep:"hostel", accommodation:"The Freezer Hostel, Rif (thefreezerhostel.com)",
      tags:["hostel","hike","excursion"], lat:64.9222, lng:-23.8194,
      summary:"Kolugljúfur hidden gorge waterfall. Drangey Island boat tour — Viking outlaw island, puffin cliffs, Grettir the Strong saga. Long drive to Snæfellsnes. Kirkjufell at midnight sun. The Freezer Hostel.",
      distance:"~320km — long drive day",
      schedule:[
        {time:"8:30am", desc:"Depart Akureyri west on Ring Road"},
        {time:"10:00am", desc:"Turn south on Route 715 to Kolugljúfur canyon (free)"},
        {time:"10:30am", desc:"Kolugljúfur canyon walk — 30–60 min", note:"No guardrails. Care near edge."},
        {time:"11:30am", desc:"Drive south via Route 752 to Sauðárkrókur (~45 min)"},
        {time:"12:00pm", desc:"Drangey Island boat tour departs Sauðárkrókur marina", note:"PRE-BOOK: drangey.net. 9:30am departure daily Jun–Aug 20. Given drive time from Akureyri, book the scheduled tour time — if 9:30am tour missed, arrange a private afternoon departure in advance."},
        {time:"12:00pm", desc:"Drangey Island boat tour — 4 hours (25 min boat each way, 2.5 hrs on island)"},
        {time:"4:00pm", desc:"Return to Sauðárkrókur marina. Drive south and west toward Snæfellsnes (~200km, ~2.5 hrs)"},
        {time:"7:00pm", desc:"Arrive Snæfellsnes peninsula. Ytri Tunga seal colony (free, 15 min)", note:"Signs off Route 54. Short walk to rocky point. Harbour seals completely accustomed to quiet visitors."},
        {time:"8:00pm", desc:"Kirkjufell mountain + Kirkjufellsfoss viewpoint (free)"},
        {time:"8:30pm", desc:"Check in The Freezer Hostel, Rif", note:"thefreezerhostel.com, +354 833 8200. Converted fish-freezing plant. Art everywhere. Owner Kári plays guitar most evenings."},
        {time:"11:30pm", desc:"Drive 10 min back to Kirkjufell for midnight golden light", note:"Mountain glows gold 11:30pm–1am. The great photographic moment of Snæfellsnes."},
      ],
      hikes:[
        {name:"Kolugljúfur Canyon Walk", distance:"1.5km", difficulty:"Easy", gain:"50m", time:"30–60 min",
        desc:"'Kola's Gorge' — carved into red-orange basalt by the Víðidalsá river. Multiple waterfalls in the gorge. The standout: in strong wind one waterfall is blown upward by canyon air currents, spraying skyward. Completely unknown to most international visitors. Free. No guardrails."},
        {name:"Drangey Island Cliff Hike", distance:"~3km on island", difficulty:"Moderate (steep sections with ropes)", gain:"180m", time:"2.5 hrs on island",
        desc:"Drangey is a flat-topped palagonite rock, 180m high, rising sheer from Skagafjörður fjord. The only path to the summit is a man-made route along the cliff face — steep in places with ropes and chains for assistance, and a ladder on the final ascent. During the climb, puffins rest on the path within metres of you. Your guide tells the saga of Grettir the Strong, the Viking outlaw who lived here for three years in exile before being slain at age 44. Thousands of seabirds: puffins, guillemots, gannets, kittiwakes, razorbills, gyrfalcons."},
      ],
      excursions:[
        {name:"Drangey Island Boat Tour", operator:"Drangey Tours (drangey.net)", price:"~$80pp", duration:"4 hrs (25 min boat each way)",
        url:"https://www.drangey.net",
        desc:"Departs Sauðárkrókur marina — 25 min boat ride to the island. Daily tours Jun 1–Aug 20 at 9:30am. Given your drive from Akureyri, contact Drangey Tours in advance (drangey.net) to confirm the scheduled departure or arrange a private afternoon time. The island is a puffin colony and sheer seabird cliff rookery, with guided hike to the 180m summit via the only accessible path (ropes + chains + ladder). Guides tell the full Grettir the Strong saga throughout. Not up for the hike? You can stay on the boat or relax in the small harbour. Coffee provided on the island."},
      ],
      tips:[
        "Book Drangey Tours well in advance — drangey.net. Given the 9:30am standard departure and your drive from Akureyri, either leave Akureyri very early, or contact Drangey Tours before the trip to arrange a private afternoon time.",
        "Kirkjufell midnight: set an alarm. 10-minute drive from The Freezer. The golden light on this mountain is one of Iceland's iconic photographic moments and requires almost no effort.",
        "The Freezer Hostel: talk to Kári, the owner. The conversion story and the art throughout the building are genuinely interesting.",
      ],
      warnings:[
        "Kolugljúfur: no guardrails on the canyon rim. Take care near the edge.",
        "Day 14 is the longest drive day (~320km). Start early from Akureyri.",
      ],
      costs:{accommodation:45, food:25, activities:80}
    },
    // ── DAY 15 ────────────────────────────────────────────────────────────────
    {
      num:15, date:"Jul 14", dow:"Monday",
      title:"Snæfellsjökull + Arnarstapi + Seltún → KEF 4pm",
      sleep:"—", accommodation:"Flight departs KEF 4:00pm",
      tags:["hike"], lat:63.8958, lng:-22.0548,
      summary:"Arnarstapi coastal trail and Gatklettur circular arch. Snæfellsjökull National Park glacier tip — Jules Verne's Journey to the Centre of the Earth. Seltún geothermal mud pots en route. Return truck. 4pm departure.",
      distance:"~250km",
      schedule:[
        {time:"7:30am", desc:"Arnarstapi — coastal trail + Gatklettur arch hike (1.5 hrs)"},
        {time:"9:30am", desc:"Hellnar viewpoint + basalt shore walk (15 min)"},
        {time:"10:00am", desc:"Drive to Snæfellsjökull NP glacier tip — free drive-in", note:"Route 574 along the peninsula tip. Jules Verne set Journey to the Centre of the Earth here. Arctic fox tracks sometimes visible on snow near the glacier."},
        {time:"10:30am", desc:"OPTIONAL: Vatnshellir lava cave guided tour (~$20pp, 45 min)", note:"8,000-year-old lava tube, signed on Route 574. Tours depart hourly. Book on-site. Cave temperature ~4°C — warm layer essential."},
        {time:"11:15am", desc:"LEAVE SNÆFELLSNES — hard deadline for 4pm flight", note:"No exceptions. Drive south on Route 54, east on Ring Road, south toward Reykjanes (~2 hrs)."},
        {time:"1:15pm", desc:"Seltún geothermal area, Reykjanes peninsula (25 min stop)", note:"FREE. Exit toward Krýsuvík. Boardwalk through bubbling mudpots, steaming fumaroles, sulphur-stained earth. Adds only 20 min. Worth every second."},
        {time:"1:45pm", desc:"Fill fuel at Orkan on Reykjanesbraut before rental return", note:"Most contracts require full tank. Fill before the airport."},
        {time:"2:00pm", desc:"Return truck to KEF rental lot", note:"Allow minimum 2 hours before departure. Clean truck bed. Fold and latch RTT correctly. Note any damage before they do."},
        {time:"2:30pm", desc:"Terminal check-in + security", note:"KEF security can be very long in peak July. Allow 60 min minimum."},
        {time:"3:00pm", desc:"Duty-free at KEF", note:"Brennivín (the Black Death caraway aquavit), Icelandic gin, skyr chocolate, Nói Síríus chocolate, lopapeysa wool. VAT refund desk near Arrivals."},
        {time:"4:00pm", desc:"FLIGHT DEPARTS. Iceland done."},
      ],
      hikes:[
        {name:"Arnarstapi–Hellnar Coastal Trail + Gatklettur Arch", distance:"5km RT", difficulty:"Easy", gain:"50m", time:"1.5 hrs",
        desc:"One of Iceland's best short coastal walks. Path follows lava coastline between the two villages past basalt sea stacks, sea arches, caves, and seabird colonies. Gatklettur ('Hole Rock') — a perfect circular arch through solid basalt promontory, framing ocean beyond — is the centrepiece. Fulmars, kittiwakes, Arctic terns nesting on every ledge. From Hellnar, a short detour leads to a sheltered sea cave at low tide."},
      ],
      excursions:[],
      tips:[
        "Leave Snæfellsnes by 11:15am — the 4pm flight has no margin for delay.",
        "Vatnshellir lava cave adds 45 min. Only do it if you're ahead of schedule. No advance booking needed.",
        "Seltún is directly on the route to KEF and adds only 20 min — genuinely worth not skipping.",
        "KEF duty-free: Brennivín is the classic Icelandic spirit. Much cheaper here than anywhere in Iceland.",
        "Return truck: rental companies charge for dirty truck beds. Sweep it out. Check for damage.",
      ],
      warnings:[
        "HARD DEADLINE: flight 4:00pm. Leave Snæfellsnes tip by 11:15am. Return truck by 2:00pm. Clear security by 3:00pm.",
        "Fill fuel before rental return — most contracts require a full tank.",
      ],
      costs:{food:20}
    },
  ],

  regions:{
    south:[1,2,3,4,5,6,7,8],
    east:[8,9,10],
    north:[11,12,13,14],
    west:[14,15],
  },

  budget:{
    fixed:[
      {label:"4x4 truck rental — 15 days, F-road insurance", sub:"Confirm F88 + F206/F207 in writing. Full-size spare tyre.", pp:675, total:1350},
      {label:"Iceland Camping Card — 2 adults, 28 nights", sub:"campingcard.is — covers Skaftafell, Hlíð Mývatn, and others.", pp:94, total:187},
      {label:"Travel insurance — must cover glacier climbing + canyoning", sub:"Confirm both activities explicitly covered in writing.", pp:60, total:120},
    ],
    accommodation:[
      {label:"Hostel nights × 8 (avg $47pp)", sub:"Loft HI · Midgard · Vík HI · Höfn HI · East GH · Akureyri GH · Freezer", pp:376, total:752},
      {label:"Camp nights × 7 (avg $17pp)", sub:"Landmannalaugar · Þakgil · Blágil · Skaftafell · Stafafell · Hlíð · Dreki", pp:119, total:238},
    ],
    food:[
      {label:"15 days mixed self-catering — avg $22/day", sub:"Bónus shops. Cook from truck. 2 restaurant meals: Höfn langoustine + Akureyri reindeer burger.", pp:330, total:660},
    ],
    activities:[
      {label:"Glacier Xtreme ice climbing — Falljökull", sub:"adventures.is — BOOK NOW — Day 7", pp:242, total:484},
      {label:"Canyoning under Vatnajökull — Ice Guardians", sub:"ice-guardians.com — BOOK NOW — Day 8", pp:278, total:556},
      {label:"Drangey Island boat tour", sub:"drangey.net — Day 14", pp:80, total:160},
      {label:"Forest Lagoon — Akureyri evening", sub:"forestlagoon.is — Day 13", pp:48, total:96},
      {label:"Þórsmörk Sterna bus return", sub:"sterna.is — non-optional access — Day 4", pp:44, total:88},
      {label:"Hallgrímskirkja tower", sub:"Day 1", pp:11, total:22},
    ],
    fuel:[
      {leg:"Day 1: KEF → Reykjavík", km:60, cost:8},
      {leg:"Day 2: Reykjavík → Háifoss → Seljalandsfoss → Midgard", km:220, cost:27},
      {leg:"Day 3: Midgard → Landmannalaugar F208", km:180, cost:22},
      {leg:"Day 4: Landmannalaugar → Skógafoss → Þórsmörk → Þakgil", km:130, cost:16},
      {leg:"Day 5: Þakgil → Dyrhólaey → Vík", km:80, cost:10},
      {leg:"Day 6: Vík → Fjáðrárgljúfur → F206/F207 Laki → Blágil", km:200, cost:35},
      {leg:"Day 7: Blágil → Skaftafell (Glacier Xtreme)", km:80, cost:10},
      {leg:"Day 8: Skaftafell → Diamond Beach → Haukafell canyoning → Höfn", km:110, cost:14},
      {leg:"Day 9: Höfn → East Fjords → Stafafell", km:180, cost:22},
      {leg:"Day 10: Stafafell → Stuðlagil → Seyðisfjörður → Egilsstaðir", km:200, cost:25},
      {leg:"Day 11: Egilsstaðir → Goðafoss → Mývatn", km:175, cost:22},
      {leg:"Day 12: Mývatn → F88 → Askja → Dreki and back", km:240, cost:49},
      {leg:"Day 13: Dreki → F88 exit → Akureyri", km:200, cost:25},
      {leg:"Day 14: Akureyri → Kolugljúfur → Sauðárkrókur (Drangey) → Snæfellsnes", km:320, cost:40},
      {leg:"Day 15: Snæfellsnes → Seltún → KEF", km:210, cost:26},
    ],
    parking:[
      {site:"Háifoss / Road 332 (Day 2)", cost:8},
      {site:"Seljalandsfoss (Day 2)", cost:4},
      {site:"Skógafoss (Day 4)", cost:4},
      {site:"Skaftafell NP (Day 7)", cost:4},
      {site:"Diamond Beach (Day 8)", cost:4},
      {site:"Fjáðrárgljúfur canyon (Day 6)", cost:4},
      {site:"Dyrhólaey + Reynisfjara (Day 5)", cost:8},
      {site:"Hverfjall, Mývatn (Day 11)", cost:4},
      {site:"Stuðlagil Canyon (Day 10)", cost:4},
      {site:"Snæfellsjökull NP + Arnarstapi (Day 15)", cost:8},
      {site:"Seltún, Reykjanes (Day 15)", cost:3},
      {site:"Goðafoss (Day 11)", cost:3},
      {site:"Misc Ring Road pullouts", cost:10},
    ],
  },

  checklist:[
    {section:"Book immediately — do today", badge:"urgent", items:[
      {text:"Glacier Xtreme ice climbing — Falljökull / Vatnajökull", sub:"Day 7 (Jul 6) · ~$242pp · Max 6 people · July sells out within days of opening", url:"https://adventures.is/iceland/day-tours/glacier-tours/glacier-tours-on-vatnajokull/glacier-xtreme-and-ice-climbing/"},
      {text:"Canyoning under Vatnajökull — Ice Guardians", sub:"Day 8 (Jul 7) · ~$278pp (34,900 ISK) · Only canyoning operator in Iceland", url:"https://ice-guardians.com/tour/half-day-canyoning-under-vatnajokull/"},
      {text:"Loft HI Hostel, Reykjavík — Bankastræti 7", sub:"Night 1 (Jun 30) · hostel.is", url:"https://www.hostel.is"},
      {text:"Midgard Base Camp, Hvolsvöllur", sub:"Night 2 (Jul 1) · midgardbasecamp.is", url:"https://www.midgardbasecamp.is"},
      {text:"Vík HI Hostel", sub:"Night 5 (Jul 4) · fills very fast in July · hostel.is", url:"https://www.hostel.is"},
      {text:"Höfn HI Hostel", sub:"Night 8 (Jul 7) · hostel.is", url:"https://www.hostel.is"},
      {text:"Þakgil canyon campsite", sub:"Night 4 (Jul 3) · thakgil.is or +354 893 4889", url:"https://www.thakgil.is"},
      {text:"Sterna highland bus — Þórsmörk return", sub:"Day 4 (Jul 3) · $44pp · must pre-book · sterna.is", url:"https://www.sterna.is"},
    ]},
    {section:"Book within 1–2 weeks", badge:"soon", items:[
      {text:"East Guesthouse, Egilsstaðir", sub:"Night 10 (Jul 9) · eastguesthouse.is", url:"https://www.eastguesthouse.is"},
      {text:"Akureyri Guesthouse", sub:"Night 13 (Jul 12) · search Booking.com · quieter than Backpackers"},
      {text:"The Freezer Hostel, Rif, Snæfellsnes", sub:"Night 14 (Jul 13) · thefreezerhostel.com", url:"https://www.thefreezerhostel.com"},
      {text:"Forest Lagoon, Akureyri — evening slot", sub:"Day 13 (Jul 12) evening · ~$44–52pp · forestlagoon.is", url:"https://www.forestlagoon.is"},
      {text:"Drangey Island boat tour — Sauðárkrókur marina", sub:"Day 14 (Jul 13) · ~$80pp · Contact drangey.net to confirm departure time given drive from Akureyri", url:"https://www.drangey.net"},
      {text:"Landmannalaugar parking reservation (if arriving 9am–4pm)", sub:"Day 3 (Jul 2) · fi.is mountain huts page", url:"https://www.fi.is/en/mountain-huts/all-mountain-huts/landmannalaugar"},
    ]},
    {section:"Accommodation contacts — all 15 nights", badge:"info", items:[
      {text:"Night 1 — Loft HI Hostel, Bankastræti 7, Reykjavík", sub:"+354 553 8140 · hostel.is · check-in 2pm"},
      {text:"Night 2 — Midgard Base Camp, Hvolsvöllur", sub:"midgardbasecamp.is · +354 578 3370"},
      {text:"Night 3 — Landmannalaugar campsite", sub:"+354 860 3335 · fi.is · NOT on Camping Card · ~$25pp · pay at hut"},
      {text:"Night 4 — Þakgil canyon campsite", sub:"+354 893 4889 · thakgil.is · cave dining room · hot showers"},
      {text:"Night 5 — Vík HI Hostel", sub:"hostel.is · fills fast · kitchen available"},
      {text:"Night 6 — Blágil hut campsite (F207 loop)", sub:"+354 487 4840 · NOT on Camping Card · ~$15pp"},
      {text:"Night 7 — Skaftafell NP campsite", sub:"Camping Card accepted · hot showers + laundry"},
      {text:"Night 8 — Höfn HI Hostel", sub:"+354 478 1736 · hostel.is · glacier terrace views"},
      {text:"Night 9 — Stafafell Nature Park", sub:"+354 699 6684 · call to confirm open · ~$14pp"},
      {text:"Night 10 — East Guesthouse, Egilsstaðir", sub:"+354 857 0804 · eastguesthouse.is"},
      {text:"Night 11 — Hlíð campsite, Lake Mývatn", sub:"+354 899 6203 · Camping Card · HEAD NETS ESSENTIAL"},
      {text:"Night 12 — Dreki hut campsite (F88/F910 junction)", sub:"ffa.is · NOT on Camping Card · ~$18pp · rangers on site"},
      {text:"Night 13 — Akureyri Guesthouse", sub:"Book via Booking.com · quieter than Backpackers"},
      {text:"Night 14 — The Freezer Hostel, Rif", sub:"+354 833 8200 · thefreezerhostel.com"},
    ]},
    {section:"Call / confirm before departure", badge:"before", items:[
      {text:"Rental company: F-road insurance in writing — F88, F206, F207", sub:"Full-size spare tyre (not space-saver). RTT height clears campsite barriers."},
      {text:"Stafafell campsite open Jul 8 — +354 699 6684"},
      {text:"Blágil hut campsite available Jul 5 — +354 487 4840"},
      {text:"Travel insurance: glacier climbing + canyoning explicitly covered", sub:"Call insurer, get written confirmation before departure."},
      {text:"Drangey Tours: confirm departure time given Akureyri drive", sub:"drangey.net — standard 9:30am may need private afternoon slot. Arrange in advance."},
      {text:"Ice Guardians: confirm exact start time + meetpoint", sub:"+354 898 2277 · info@ice-guardians.com · Haukafell Campsite, Hornafjörður"},
    ]},
    {section:"Purchase before departure", badge:"before", items:[
      {text:"Iceland Camping Card — 2 adults, 28 nights", sub:"€179 / ~$187 · campingcard.is", url:"https://www.campingcard.is"},
      {text:"Head nets × 2 (sealed face type)", sub:"ABSOLUTELY ESSENTIAL for Mývatn, Day 11. Buy at REI or Amazon before leaving."},
      {text:"Water filter — Sawyer Squeeze or BeFree", sub:"For Lónsöræfi canyon (Day 9) and Askja highland (Day 12)."},
      {text:"Blackout sleep mask × 2", sub:"Midnight sun never gets dark in July. Essential from Night 1."},
      {text:"20-litre fuel jerry can (HDPE approved)", sub:"Fill at Mývatn before F88 on Day 12. Mandatory."},
      {text:"Tow rope — rated to vehicle weight + 50%", sub:"Minimum 5-tonne. Buy before leaving — expensive in Iceland."},
      {text:"Tyre plug kit + portable 12V inflator", sub:"For F-road lava punctures."},
      {text:"First aid kit (adventure-rated)", sub:"Compeed blisters, bandages, antiseptic, pain relief, antihistamine."},
      {text:"Waterproof phone case / dry bag for canyoning", sub:"Required for Ice Guardians day. Loksak dry bag works well."},
      {text:"Trekking poles × 2 pairs", sub:"Essential for Viti crater descent (slippery), Bláhnúkur, Drangey cliff path, Lónsöræfi."},
    ]},
    {section:"Download + bookmark", badge:"before", items:[
      {text:"Parka.is — set up account + payment before landing", sub:"Camera-enforced parking at ALL major Iceland sites.", url:"https://parka.is"},
      {text:"112 Iceland app", sub:"One button sends GPS to SAR. Mandatory for F-road days.", url:"https://www.112.is"},
      {text:"Gaia GPS — download Iceland offline maps", sub:"Essential for Lónsöræfi (Day 9) and Remundargil (Day 5)."},
      {text:"Wikiloc — save Remundargil + Lónsöræfi Hvítserkur routes offline"},
      {text:"Bookmark umferdin.is/en/road/91381 — F207 Laki live status", sub:"Check morning of Day 6 (Jul 5).", url:"https://umferdin.is/en/road/91381"},
      {text:"Bookmark safetravel.is", sub:"Register F88 (Day 12) and F206 (Day 6) before entering.", url:"https://safetravel.is"},
      {text:"Bookmark umferdin.is/en — general road conditions", url:"https://umferdin.is/en"},
      {text:"Bookmark en.vedur.is — Iceland 48hr weather forecast", url:"https://en.vedur.is"},
      {text:"Google Maps — download Iceland offline map pack"},
    ]},
    {section:"Clothing + gear", badge:"gear", items:[
      {text:"Waterproof jacket (taped seams) × each", sub:"Keep in truck cab AT ALL TIMES."},
      {text:"Waterproof trousers × each"},
      {text:"Merino wool base layer top × 3 each"},
      {text:"Merino wool base layer bottom × 2 each"},
      {text:"Warm mid-layer (fleece or down puffy) × each", sub:"Askja/Dreki highlands near freezing even in July."},
      {text:"Warm hat + gloves × each"},
      {text:"Hiking boots (stiff, ankle support, waterproof) × each", sub:"Break in 2+ weeks before departure."},
      {text:"Camp sandals × each"},
      {text:"Dry bags (5L, 10L, 20L) for truck bed", sub:"Everything in truck bed must be waterproofed."},
      {text:"Camp stove + fuel canisters", sub:"Buy gas in Iceland — cannot fly with pressurised canisters."},
      {text:"Cooking pot, pan, utensils, plates, mugs"},
      {text:"Power banks × 2 (20,000mAh+)", sub:"No power at Dreki or any F-road camp."},
      {text:"Sunscreen SPF 50+ × 2 tubes", sub:"Midnight sun UV is real on glaciers and lagoons."},
      {text:"Polarised sunglasses × each", sub:"Essential on the glacier — cuts ice and water glare."},
      {text:"Reusable water bottles × 2 each (1L minimum)"},
      {text:"Quick-dry travel towel × each", sub:"For canyoning, Viti swim, Forest Lagoon, campsite showers."},
      {text:"Personal medications + surplus"},
      {text:"Small padlock for hostel lockers"},
    ]},
    {section:"Vehicle check (on collection at KEF)", badge:"gear", items:[
      {text:"Full-size spare tyre confirmed — not a space-saver", sub:"Insist on this before leaving the lot."},
      {text:"Tyre pressure checked on collection"},
      {text:"F-road insurance confirmed in writing — F88, F206, F207"},
      {text:"Duct tape (large roll) in truck"},
      {text:"Windscreen washer fluid level checked"},
      {text:"Jump cables or compact battery jump starter"},
      {text:"Emergency bivvy bag × 2"},
      {text:"Head torch × 2 + spare batteries"},
      {text:"RTT opens and closes correctly — test before leaving lot"},
      {text:"All existing damage noted on collection form"},
    ]},
    {section:"Day-of reminders", badge:"urgent", items:[
      {text:"Day 4 (Jul 3): Skógar river trail HARD STOP at 10:15am", sub:"Set a phone alarm. The Sterna bus cannot be missed."},
      {text:"Day 6 (Jul 5): check umferdin.is/en/road/91381 for F206/F207 status", sub:"If CLOSED → drive direct to Skaftafell. Day 7 unaffected."},
      {text:"Day 8 (Jul 7): bring towel + dry clothes for canyoning", sub:"Leave in truck. Ice Guardians provides wetsuit, helmet, harness."},
      {text:"Day 12 (Jul 11): fill fuel MAX + 20L jerry can at Mývatn before F88", sub:"Non-negotiable. Zero fuel on F88."},
      {text:"Day 12 (Jul 11): register F88 route at safetravel.is before entering"},
      {text:"Day 15 (Jul 14): leave Snæfellsnes glacier tip by 11:15am", sub:"Hard deadline. 4pm KEF departure."},
      {text:"Day 15 (Jul 14): fill fuel at Orkan before rental return"},
      {text:"Every F-road day: walk every river crossing before driving"},
    ]},
    {section:"Emergency contacts", badge:"info", items:[
      {text:"Icelandic emergency — 112", sub:"112 Iceland app sends GPS automatically."},
      {text:"Road conditions + SAR — 1777 (24hrs)"},
      {text:"Your rental company emergency number", sub:"Save in phone AND write on paper."},
      {text:"Ice Guardians — +354 898 2277 · info@ice-guardians.com", sub:"Day 8 canyoning operator."},
      {text:"Arctic Adventures — adventures.is", sub:"Day 7 Glacier Xtreme operator."},
      {text:"Drangey Tours — drangey.net", sub:"Day 14 boat tour operator."},
      {text:"Forest Lagoon — forestlagoon.is · +354 xxx xxxx", sub:"Day 13 geothermal spa."},
      {text:"Travel insurance 24hr helpline", sub:"Save number in phone AND on paper."},
      {text:"KEF Airport — +354 425 6000"},
    ]},
  ],
};
