// ── Iceland Trip Data ────────────────────────────────────────────────────────

const TRIP_DATA = {
  days: [
    {
      num: 1, date: "Jun 30", title: "Arrive Reykjavík",
      sleep: "hostel", accommodation: "Loft HI Hostel, Reykjavík",
      tags: ["hostel"],
      costPP: 192,
      lat: 64.1466, lng: -21.9426,
      color: "#4a9eff",
      summary: "Land 10:30am KEF. Big grocery shop. Explore Reykjavík. Sky Lagoon evening.",
      schedule: [
        { time: "10:30am", desc: "Land at KEF airport", note: "Allow 30 min baggage + customs" },
        { time: "11:15am", desc: "Pick up 4x4 truck at rental company", note: "Confirm F-road insurance in writing before leaving the lot" },
        { time: "12:00pm", desc: "Bónus supermarket — BIG shop", note: "Stock up for 3-4 days on the road. Aim for ~$55 for 2 people." },
        { time: "1:30pm", desc: "Check in Loft HI Hostel, Bankastrǣti 7" },
        { time: "2:30pm", desc: "Hallgrímskirkja church tower", note: "1,500 ISK (~$11pp). Best city panorama." },
        { time: "3:30pm", desc: "Sun Voyager sculpture + Harpa concert hall walk", note: "Free. Stunning architecture on the waterfront." },
        { time: "5:00pm", desc: "Bæjarins Beztu Pylsur hot dogs", note: "Order 'eina með öllu' — one with everything. ~$4." },
        { time: "7:00pm", desc: "Sky Lagoon (pre-booked Saman pass ~$100pp)", note: "7-step geothermal ritual. Infinity pool over the ocean. Return by 10pm." },
      ],
      hikes: [],
      excursions: [
        { name: "Sky Lagoon — Saman Pass", operator: "skylagoon.com", price: "$100pp", duration: "2-3 hrs", desc: "Geothermal infinity pool overlooking the ocean, 10 min south of the city centre. The 7-step ritual includes steam room, cold plunge, sauna, scrub, and the signature infinity pool." }
      ],
      tips: ["First 48 hours: jet lag is real. Sky Lagoon in the evening helps reset your body clock.", "Iceland tap water is safe and delicious. Never buy bottled water."],
      warnings: [],
      costs: { accommodation: 45, food: 36, activities: 111 }
    },
    {
      num: 2, date: "Jul 1", title: "Háifoss + Landmannalaugar",
      sleep: "camp", accommodation: "Landmannalaugar campsite",
      tags: ["camp", "hike", "froad"],
      costPP: 300,
      lat: 63.9906, lng: -19.0607,
      color: "#22c55e",
      summary: "Route 332 to Háifoss waterfall gorge, then F208 north to Landmannalaugar rainbow mountains.",
      schedule: [
        { time: "7:30am", desc: "Depart Reykjavík on Ring Road east" },
        { time: "9:00am", desc: "Turn onto Route 32, then 327/332 to Háifoss", note: "Rough gravel — high clearance needed. Drive slowly." },
        { time: "9:30am", desc: "Háifoss waterfall — rim viewpoint + gorge descent hike", note: "Allow 2 hrs for both trails." },
        { time: "12:00pm", desc: "Drive south, rejoin Ring Road, head east to Hrauneyjar junction", note: "F208 north entrance near Hrauneyjar. NO river crossings on this section — safe for your rental." },
        { time: "2:30pm", desc: "Arrive Landmannalaugar via F208", note: "PRE-BOOK parking if arriving 9am-4pm at fi.is" },
        { time: "3:00pm", desc: "Brennisteinsalda rainbow volcano loop hike" },
        { time: "5:00pm", desc: "Bláhnúkur Blue Peak hike", note: "Best panorama in all of Landmannalaugar" },
        { time: "7:30pm", desc: "Hot spring soak at the hut — FREE with campsite stay" },
        { time: "9:00pm", desc: "Camp at Landmannalaugar (~$25pp, NOT on Camping Card)" },
      ],
      hikes: [
        { name: "Háifoss Gorge Descent", distance: "4km RT", difficulty: "Moderate", gain: "300m", time: "1.5-2 hrs", desc: "Scramble into the canyon to the base of Iceland's 4th highest waterfall (122m). Stand in the mist at the base. Stranger Things S8 filming location. Almost nobody does the gorge trail — you'll likely have it to yourself." },
        { name: "Brennisteinsalda Loop", distance: "4km", difficulty: "Moderate", gain: "200m", time: "90 min", desc: "Circuit around the steam-venting rainbow volcano. Red, green, yellow, and white layers from different volcanic minerals. Steam vents hiss from the ground beside the path." },
        { name: "Bláhnúkur Blue Peak", distance: "6km RT", difficulty: "Moderate-Challenging", gain: "350m", time: "2.5 hrs", desc: "Best single viewpoint in Landmannalaugar. The entire valley of rhyolite mountains spreads in every direction. Push through the final steep section — the summit view is worth every step." },
      ],
      excursions: [],
      tips: ["Landmannalaugar 2026: parking now requires online reservation if arriving between 9am-4pm. Book at fi.is before departure.", "The hot spring soak is included with camping — it's small and low-key, nothing like a commercial spa, but soaking in a natural thermal pool under the midnight sun is extraordinary."],
      warnings: ["F208 north route has NO river crossings. Do NOT attempt F225 southern approach — river crossings that invalidate rental insurance."],
      costs: { accommodation: 25, food: 22, activities: 0, parking: 10 }
    },
    {
      num: 3, date: "Jul 2", title: "Skógafoss + Þórsmörk + Þakgil Camp",
      sleep: "camp", accommodation: "Þakgil Canyon Campsite",
      tags: ["camp", "hike", "excursion"],
      costPP: 96,
      lat: 63.5309, lng: -18.8887,
      color: "#22c55e",
      summary: "Skógafoss waterfall trail. Sterna bus into Þórsmörk valley. Cave canyon camp at Þakgil.",
      schedule: [
        { time: "7:00am", desc: "Exit Landmannalaugar early via F208 south" },
        { time: "9:00am", desc: "Skógafoss waterfall — staircase + river trail hike", note: "Parking ~$8 via Parka.is" },
        { time: "11:30am", desc: "Drive to Hvolsvöllur, board Sterna bus to Þórsmörk", note: "PRE-BOOK: sterna.is, ~$44pp return. Leave truck at Midgard or Hvolsvöllur parking." },
        { time: "1:30pm", desc: "Arrive Þórsmörk valley. Stakkholtsgjá canyon hike" },
        { time: "3:30pm", desc: "Valahnúkur summit hike — best viewpoint of the valley" },
        { time: "5:00pm", desc: "Return bus to Hvolsvöllur" },
        { time: "6:00pm", desc: "Pick up truck. Drive Road 214 to Þakgil (~45 min gravel)", note: "NOT an F-road. Steep in places but manageable." },
        { time: "7:00pm", desc: "Arrive Þakgil canyon campsite. Book: thakgil.is / +354 893 4889" },
      ],
      hikes: [
        { name: "Skógar River Trail Upstream", distance: "Up to 14km one way", difficulty: "Moderate-Challenging", gain: "1000m to Fimmvörðuháls", time: "Go as far as legs allow", desc: "Follow the Skóga river past 10+ named waterfalls in succession — each more dramatic than the last. The further you go, the more crowd-free. Most visitors turn around at 2-4km. The full route ends at the volcanic ridge between Eyjafjallajökull and Mýrdalsjökull. Start at the staircase top." },
        { name: "Stakkholtsgjá Canyon", distance: "5km RT", difficulty: "Moderate", gain: "100m", time: "2 hrs", desc: "A narrow slot canyon that opens into a cave at the end — with a waterfall dropping inside the cave. Completely otherworldly. The canyon walls close in as you walk and the light shifts to a narrow strip above you. One of the great secret hikes in Iceland." },
        { name: "Valahnúkur Summit", distance: "5km", difficulty: "Moderate", gain: "300m", time: "2.5 hrs", desc: "Best single panorama of the Þórsmörk valley. Eyjafjallajökull, Mýrdalsjökull, and Tindfjallajökull glaciers on three sides. The Fimmvörðuháls volcanic ridge visible to the north." },
      ],
      excursions: [
        { name: "Sterna Highland Bus — Þórsmörk Return", operator: "sterna.is", price: "$44pp", duration: "All day transport", desc: "The F249 river crossings into Þórsmörk are among Iceland's most dangerous and void rental car insurance. The Sterna bus takes you safely across and back. Departs Hvolsvöllur, arrives Volcano Huts area. Book in advance — fills up." }
      ],
      tips: ["Þakgil campsite has a cave dining room carved directly into the canyon cliff face. Eat breakfast there in the morning before the trail.", "From camp you can see Katla glacier on the ridgeline on clear mornings."],
      warnings: [],
      costs: { accommodation: 20, food: 18, activities: 44 }
    },
    {
      num: 4, date: "Jul 3", title: "Þakgil Hike + Katla Ice Cave + Vík",
      sleep: "hostel", accommodation: "Vík HI Hostel",
      tags: ["hostel", "hike", "excursion"],
      costPP: 167,
      lat: 63.4190, lng: -19.0055,
      color: "#4a9eff",
      summary: "Morning Remundargil canyon hike. Katla ice cave super-jeep tour. Dyrhólaey + Reynisfjara.",
      schedule: [
        { time: "7:00am", desc: "Morning hike from Þakgil camp — Remundargil loop", note: "12.5km, allow 3-4 hrs" },
        { time: "11:00am", desc: "Pack camp, drive to Vík area (~45 min)" },
        { time: "1:00pm", desc: "Katla ice cave super-jeep tour (pre-booked)", note: "Book: troll.is or katlatrack.is, ~$90pp. Departs from Vík." },
        { time: "4:00pm", desc: "Dyrhólaey sea arch + puffin cliffs", note: "July peak nesting season. Parking ~$8." },
        { time: "5:30pm", desc: "Reynisfjara black sand beach", note: "⚠️ NEVER turn your back on the ocean." },
        { time: "6:30pm", desc: "Check in Vík HI Hostel. Cook dinner." },
      ],
      hikes: [
        { name: "Remundargil Canyon Loop", distance: "12.5km", difficulty: "Moderate", gain: "250m", time: "3-5 hrs", desc: "From Þakgil campsite, this loop takes you along canyon rims with views of Katla glacier. The route goes into the canyon gorge and back along the rim. Bring water and snacks — no facilities on trail. Download Wikiloc trail before setting off as parts are unmarked." },
      ],
      excursions: [
        { name: "Katla Ice Cave Super-Jeep Tour", operator: "Troll Expeditions / Katla Guide", price: "$90pp", duration: "2-3 hrs", desc: "A modified super-jeep drives you onto Mýrdalsjökull glacier, which sits directly over the active Katla volcano. The ice cave walls show distinct black ash layers from past Katla eruptions — unique in Iceland. Completely different experience from Skaftafell's blue ice cave. Geological and dramatic. Only accessible by super-jeep." }
      ],
      tips: ["Dyrhólaey is Iceland's largest natural arch. The puffin colonies nest on the cliff face directly below the lighthouse platform in July — look down.", "The Katla ice cave is underground at altitude — bring a warm layer even on a warm day."],
      warnings: ["Reynisfjara: sneaker waves here kill people every year. No warning. Never turn back to the ocean. Keep 30m from the waterline."],
      costs: { accommodation: 45, food: 18, activities: 90 }
    },
    {
      num: 5, date: "Jul 4", title: "Laki Craters F206/F207",
      sleep: "camp", accommodation: "Blágil Hut Campsite",
      tags: ["camp", "hike", "froad"],
      costPP: 55,
      lat: 64.0707, lng: -18.2378,
      color: "#f59e0b",
      summary: "Fjáðrárgljúfur canyon quick stop, then F206/F207 highland loop through Laki craters. Camp at Blágil.",
      schedule: [
        { time: "6:30am", desc: "Early departure — check road.is before leaving", note: "F206/F207 opens mid-July. If still closed, go direct to Skaftafell." },
        { time: "7:30am", desc: "Fjáðrárgljúfur canyon — quick stop", note: "Free. 30 min rim walk. Game of Thrones filming location." },
        { time: "8:30am", desc: "Turn north on F206 (Lakavegur) from Ring Road", note: "Register at safetravel.is before entering." },
        { time: "10:30am", desc: "Fagrifoss waterfall en route — stop and walk" },
        { time: "11:00am", desc: "Arrive Laki crater trailhead. Mt. Laki summit hike" },
        { time: "1:00pm", desc: "Visitor Trail through crater interior" },
        { time: "3:00pm", desc: "Continue F207 loop south back toward Ring Road" },
        { time: "5:00pm", desc: "Blágil hut campsite — set up camp", note: "+354 487 4840. Kitchen, toilets, showers." },
      ],
      hikes: [
        { name: "Mt. Laki Summit", distance: "3.5km RT", difficulty: "Moderate", gain: "200m", time: "1-2 hrs", desc: "From the ranger hut trailhead, follow the marked path to the summit of Mt. Laki. From the top you can see the entire 25km row of 130 craters stretching in both directions. The 1783 Lakagígar eruption was one of the most catastrophic in human history — killed 25% of Iceland's population and affected European weather for years." },
        { name: "Visitor Trail — Crater Interior", distance: "2km loop", difficulty: "Easy", gain: "50m", time: "1 hr", desc: "Walk directly through the inside of a volcanic crater and into the eruption fissure itself. The lava fields are covered in vivid green moss. The scale and absolute silence of the crater field is staggering. Marked trail, easy underfoot." },
      ],
      excursions: [],
      tips: ["F206 has 12+ river crossings. Drive slowly, assess each crossing before entering. Never rush a ford.", "Fill to absolute maximum before entering F206. The loop is 100+ km with no fuel."],
      warnings: ["CRITICAL: Check road.is morning of departure. F206/F207 typically opens mid-July — may be closed for your Jul 4 date. If closed, drive directly to Skaftafell.", "Register at safetravel.is before entering the F206 highland area."],
      costs: { accommodation: 18, food: 20, activities: 0, fuel: 70 }
    },
    {
      num: 6, date: "Jul 5", title: "Ice Axe Climbing + Skaftafell Blue Ice",
      sleep: "camp", accommodation: "Skaftafell campsite",
      tags: ["camp", "hike", "excursion"],
      costPP: 326,
      lat: 64.0163, lng: -16.9681,
      color: "#22c55e",
      summary: "Sólheimajökull ice axe climbing then drive to Skaftafell for Blue Ice hike and Svartifoss trail.",
      schedule: [
        { time: "8:00am", desc: "Drive from Blágil back to Ring Road, west toward Vík area" },
        { time: "10:00am", desc: "Sólheimajökull glacier parking — meet Mountain Guides", note: "PRE-BOOK: mountainguides.is, $218pp. Tour starts here." },
        { time: "10:30am", desc: "Ice Axe Climbing + Glacier Hike — 4 hours on the ice" },
        { time: "2:30pm", desc: "Drive east along Ring Road toward Skaftafell (~2hrs)" },
        { time: "4:30pm", desc: "Blue Ice Experience hike — Skaftafellsjökull glacier", note: "PRE-BOOK: mountainguides.is, $95pp. Meet at Skaftafell Base Camp." },
        { time: "8:00pm", desc: "Svartifoss waterfall trail hike", note: "Easy, 3.5km RT, 2hrs. Free." },
        { time: "10:00pm", desc: "Set up camp at Skaftafell (Camping Card accepted)" },
      ],
      hikes: [
        { name: "Svartifoss Trail", distance: "3.5km RT", difficulty: "Easy-Moderate", gain: "120m", time: "2 hrs", desc: "The Black Waterfall — drops over a curtain of dark hexagonal basalt columns. The same basalt architecture that inspired Hallgrímskirkja church. Short but visually stunning. Trailhead from Skaftafell visitor centre. Do it in the evening golden light after the glacier tours." },
      ],
      excursions: [
        { name: "Ice Axe Climbing — Sólheimajökull", operator: "Icelandic Mountain Guides (mountainguides.is)", price: "$218pp", duration: "4 hrs", desc: "The trip highlight. Hike onto the glacier, receive crampon and twin ice axe instruction, then climb a frozen wall or rappel into a crevasse. Groups ≤6 per guide. All gear included: crampons, twin axes, harness, helmet. No experience needed. Sólheimajökull is one of the most accessible glacier ice climbing venues in Europe. BOOK IMMEDIATELY — July slots fill within days of opening." },
        { name: "Blue Ice Experience — Skaftafellsjökull", operator: "Icelandic Mountain Guides (mountainguides.is)", price: "$95pp", duration: "3.5 hrs", desc: "Deeper glacier access than standard tours. Guides take you into crevasses, moulins, and blue ice formations. A different glacier tongue from the Day 6 ice climb — entirely different visual experience. Pure exploration, no technical climbing." },
      ],
      tips: ["Two different glaciers, two completely different experiences. Sólheimajökull (Day 6) is darker and more crevassed. Skaftafellsjökull (Day 6 afternoon) is bluer and more photogenic.", "Skaftafell campsite has hot showers and laundry. Use both."],
      warnings: ["Both tours must be pre-booked. Walk-ins are not possible in July."],
      costs: { accommodation: 16, food: 18, activities: 313 }
    },
    {
      num: 7, date: "Jul 6", title: "Jökulsárlón Kayak + Diamond Beach + Höfn",
      sleep: "hostel", accommodation: "Höfn HI Hostel",
      tags: ["hostel", "excursion"],
      costPP: 196,
      lat: 64.2621, lng: -15.2124,
      color: "#4a9eff",
      summary: "Kayak among floating icebergs at the glacier lagoon. Diamond Beach. Langoustine dinner in Höfn.",
      schedule: [
        { time: "9:00am", desc: "Drive from Skaftafell to Jökulsárlón (~45 min)" },
        { time: "9:30am", desc: "Jökulsárlón kayak tour (pre-booked)", note: "Book: icelagoon.is, ~$98pp. Dry suits provided." },
        { time: "12:30pm", desc: "Walk to Diamond Beach — 200m from lagoon parking", note: "Free. Ice chunks on black sand. Allow 30 min." },
        { time: "1:30pm", desc: "Drive to Höfn (~1hr)" },
        { time: "3:00pm", desc: "Check in Höfn HI Hostel. Glacier terrace views." },
        { time: "4:00pm", desc: "Explore Höfn harbour" },
        { time: "6:00pm", desc: "Langoustine dinner", note: "Höfn is Iceland's langoustine capital. Treat yourselves once — ~$30pp. Pakkhús or Hafnarbuðin." },
      ],
      hikes: [],
      excursions: [
        { name: "Jökulsárlón Kayak Tour", operator: "Local Iceberg Tours (icelagoon.is)", price: "$98pp", duration: "2-3 hrs", desc: "Paddle a sea kayak among floating icebergs at eye level. Dry suits provided. Far more intimate than the zodiac boat — groups are tiny, you can approach the bergs closely, touch them, and the silence is extraordinary. Seals often surface alongside. The icebergs calve off Breiðamerkurjökull glacier — some pure white, some deep sapphire blue, some streaked with volcanic ash." },
      ],
      tips: ["Höfn's langoustine soup is the best thing you'll eat in Iceland. Worth every króna.", "The glacier terrace at the hostel is perfect for the midnight sun — the Vatnajökull ice cap glows pink at midnight."],
      warnings: [],
      costs: { accommodation: 45, food: 55, activities: 98 }
    },
    {
      num: 8, date: "Jul 7", title: "Stafafell + Lónsöræfi Canyon",
      sleep: "camp", accommodation: "Stafafell Nature Park",
      tags: ["camp", "hike"],
      costPP: 46,
      lat: 64.4197, lng: -14.8439,
      color: "#22c55e",
      summary: "Drive to Stafafell farm campsite. Hike the extraordinary Lónsöræfi red rhyolite canyon.",
      schedule: [
        { time: "9:00am", desc: "Drive east from Höfn to Stafafell (~1.5 hrs)" },
        { time: "10:30am", desc: "Check in Stafafell Nature Park campsite", note: "Call ahead: +354 699 6684. Family farm, charming." },
        { time: "11:00am", desc: "Begin Lónsöræfi highland hike via mild F985 track" },
        { time: "12:00pm–4pm", desc: "Lónsöræfi Hvítserkur canyon hike — full afternoon" },
        { time: "5:00pm", desc: "Return to camp. Cook dinner. Cheapest day of the trip." },
      ],
      hikes: [
        { name: "Lónsöræfi Hvítserkur Canyon", distance: "Variable — 8-15km", difficulty: "Moderate", gain: "400m", time: "4-5 hrs", desc: "Iceland's most overlooked hiking area. Jagged peaks in rust red and orange rhyolite rising from a hidden valley. Virtually zero other visitors. You'll likely have the entire canyon to yourself. Trail unmarked in sections — download on Gaia GPS before setting off. Water from mountain streams only: bring a filter. Access via F985 track (mild, manageable in your 4x4)." },
      ],
      excursions: [],
      tips: ["Bring all food for the day. No facilities in the canyon. The colour of the rock in evening light is extraordinary.", "This is the quietest, most remote day of the trip. Embrace the solitude."],
      warnings: [],
      costs: { accommodation: 14, food: 18, activities: 0 }
    },
    {
      num: 9, date: "Jul 8", title: "East Fjords + Stuðlagil Canyon + Seyðisfjörður",
      sleep: "hostel", accommodation: "East Guesthouse, Egilsstaðir",
      tags: ["hostel", "hike"],
      costPP: 80,
      lat: 65.2590, lng: -14.3952,
      color: "#4a9eff",
      summary: "East Fjords coastal drive. Stuðlagil basalt column canyon. Seyðisfjörður rainbow road. Resupply Egilsstaðir.",
      schedule: [
        { time: "8:30am", desc: "Drive north from Stafafell on Ring Road — East Fjords coast" },
        { time: "11:00am", desc: "Turn north on Route 923 — 45 min drive to Stuðlagil Canyon" },
        { time: "12:00pm", desc: "Stuðlagil Canyon east side rim hike", note: "Check upstream weather first: rain = opaque white river, not turquoise. Morning = best colour." },
        { time: "2:30pm", desc: "Drive back south to Ring Road, then east over mountain pass to Seyðisfjörður" },
        { time: "3:30pm", desc: "Seyðisfjörður — rainbow road walk, blue church, café stop" },
        { time: "5:00pm", desc: "Drive back over mountain to Egilsstaðir (~45 min)" },
        { time: "6:00pm", desc: "Check in East Guesthouse. MAJOR RESUPPLY: Bónus, fuel, camp gas, laundry." },
      ],
      hikes: [
        { name: "Stuðlagil Canyon East Rim", distance: "4-8km RT", difficulty: "Easy-Moderate", gain: "100m", time: "2-4 hrs", desc: "Hexagonal basalt columns identical to Giant's Causeway in Ireland — but here they form the walls of a narrow canyon with a turquoise glacial river. The columns rise 30m from the water. The canyon was entirely underwater until 2009 when a dam upstream was built and the water level dropped. Go as far as Stuðlafoss waterfall for the best views. Still virtually unknown to tourists outside Iceland." },
      ],
      excursions: [],
      tips: ["Egilsstaðir Bónus is your last cheap supermarket until Akureyri — stock up properly. Also refill gas canisters for the camp stove here.", "Seyðisfjörður's rainbow road leads to the most photographed blue church in Iceland. The town is an artist colony with a great café."],
      warnings: [],
      costs: { accommodation: 45, food: 25, activities: 0 }
    },
    {
      num: 10, date: "Jul 9", title: "Mývatn Volcanic Wonderland + Earth Lagoon",
      sleep: "camp", accommodation: "Hlíð Campsite, Lake Mývatn",
      tags: ["camp", "hike"],
      costPP: 117,
      lat: 65.6495, lng: -16.9187,
      color: "#22c55e",
      summary: "Goðafoss waterfall. Hverfjall crater rim hike. Dimmuborgir lava formations. Grjótagjá cave spring. Earth Lagoon.",
      schedule: [
        { time: "8:30am", desc: "Drive Ring Road west from Egilsstaðir (~2.5 hrs, 175km)" },
        { time: "10:00am", desc: "Goðafoss waterfall — quick stop", note: "Free. Right off Ring Road. 'Waterfall of the Gods'." },
        { time: "10:30am", desc: "Hverfjall volcano — crater rim hike", note: "Parking ~$8. Stay on marked path — protect the tephra." },
        { time: "1:00pm", desc: "Dimmuborgir lava formations — easy walk", note: "Free. 30-90 min. Otherworldly lava towers and arches." },
        { time: "2:30pm", desc: "Grjótagjá lava cave hot spring", note: "FREE. Game of Thrones cave (Jon Snow scene). Too hot to swim but blue glow inside is extraordinary." },
        { time: "5:00pm", desc: "Earth Lagoon Mývatn (pre-booked evening slot)", note: "~$64pp. Confirm reopening at earthlagoon.is — 2026 renovation." },
        { time: "8:00pm", desc: "Check in Hlíð campsite", note: "⚠️ HEAD NETS ON IMMEDIATELY. Zip tent straight away." },
      ],
      hikes: [
        { name: "Hverfjall Crater Rim", distance: "3km loop", difficulty: "Moderate", gain: "150m", time: "2 hrs", desc: "Climb the outer slope of this perfectly circular tephra cone (1km wide crater). From the rim you see the entire Lake Mývatn area, the lava fields, and surrounding volcanic highlands. One of Iceland's most distinctive geological features. Important: stay on the marked path — footsteps damage the fragile tephra surface permanently." },
      ],
      excursions: [
        { name: "Earth Lagoon Mývatn", operator: "earthlagoon.is", price: "~$64pp", duration: "2-3 hrs", desc: "Geothermal lagoon on a hill overlooking Lake Mývatn. After a 2026 renovation. Milky blue water from the geothermal borehole, steam rooms, multiple pools at different temperatures. Much less crowded and cheaper than Blue Lagoon. Book an evening slot to avoid the tour bus rush." },
      ],
      tips: ["Buy head nets in Egilsstaðir before arriving at Mývatn. The midges here in July are genuinely legendary — they fly into your eyes, ears, and mouth constantly. Head nets are not optional.", "Grjótagjá: the water was a comfortable swimming temperature when GoT filmed there. It's now too hot to swim but the blue interior glow is worth the short walk."],
      warnings: ["MIDGES: never open tent without immediately zipping it shut. They will fill the tent in 10 seconds flat."],
      costs: { accommodation: 16, food: 18, activities: 69 }
    },
    {
      num: 11, date: "Jul 10", title: "Askja Caldera + Viti Crater — F88",
      sleep: "camp", accommodation: "Dreki Hut",
      tags: ["camp", "hike", "froad"],
      costPP: 56,
      lat: 65.0421, lng: -16.5952,
      color: "#f59e0b",
      summary: "F88 highland drive through the world's largest lava field to Askja caldera. Swim in Viti geothermal crater. Sleep at Dreki hut.",
      schedule: [
        { time: "7:00am", desc: "Fill fuel to MAXIMUM at Mývatn + fill 20L jerry can", note: "No fuel between Mývatn and the Ring Road on the other side. None." },
        { time: "7:30am", desc: "Register route at safetravel.is before entering F88", note: "F88 entrance ~20km east of Mývatn on Ring Road." },
        { time: "8:00am", desc: "Enter F88. Drive through Ódáðahraun lava desert — 60km to Dreki (~2.5 hrs on highland gravel)" },
        { time: "10:30am", desc: "Arrive Dreki hut. Leave truck. Begin Askja caldera hike" },
        { time: "11:00am-2pm", desc: "Askja caldera hike — 8km RT from Dreki, 3-4 hrs" },
        { time: "2:30pm", desc: "Swim in Viti geothermal explosion crater", note: "FREE. Warm milky blue/green water. Swimming inside a volcanic crater." },
        { time: "4:00pm", desc: "Return to Dreki. Set up camp. Cook a big meal." },
        { time: "2:00am", desc: "Midnight sun in the highlands — sit outside with coffee" },
      ],
      hikes: [
        { name: "Askja Caldera Hike", distance: "8km RT", difficulty: "Moderate", gain: "200m", time: "3-4 hrs", desc: "From Dreki, follow the marked trail across ancient lava fields and volcanic debris to the rim of the Askja caldera. The scale only becomes apparent at the rim — a vast bowl containing the deep blue Lake Öskjuvatn. The Viti explosion crater is a 15-min walk from Öskjuvatn's shore — a 150m wide crater filled with warm milky blue geothermal water. One of the most extraordinary experiences in Iceland: swimming inside an active volcanic crater in the middle of a highland lava desert." },
      ],
      excursions: [],
      tips: ["The F88 drive takes 2.5 hrs each way. Allow a full day. The lunar landscape of Ódáðahraun (the world's largest lava field) is as dramatic as the caldera itself.", "Dreki hut: snacks and water sold on-site. Rangers present. The hut has an indoor dining room (closes 9pm). Rocky ground — you'll sleep in your rooftop tent."],
      warnings: ["CRITICAL: Fill fuel to maximum + 20L jerry can at Mývatn before entering F88. Zero fuel available on this route.", "River crossings on F88: assess each one on foot before driving. Never rush a ford.", "Bring warm layers — altitude makes it significantly colder than the Ring Road."],
      costs: { accommodation: 18, food: 20, activities: 0, fuel: 98 }
    },
    {
      num: 12, date: "Jul 11", title: "Exit F88 → Akureyri Whale Watching",
      sleep: "hostel", accommodation: "Akureyri Guesthouse",
      tags: ["hostel", "excursion"],
      costPP: 191,
      lat: 65.6814, lng: -18.0898,
      color: "#4a9eff",
      summary: "Drive back out F88. Goðafoss stop. Akureyri: whale watching, botanical garden, laundry, resupply.",
      schedule: [
        { time: "8:00am", desc: "Exit F88 (same road back, 2.5 hrs to Ring Road)" },
        { time: "10:30am", desc: "Top up fuel at first Ring Road station" },
        { time: "11:00am", desc: "Drive Ring Road west to Akureyri (~90 min)" },
        { time: "12:30pm", desc: "Check in Akureyri Guesthouse (quieter than Backpackers). Laundry + resupply." },
        { time: "2:00pm", desc: "Whale watching tour — Akureyri harbour (pre-booked)", note: "~$90pp. 3hrs. whalewatchingakureyri.is" },
        { time: "5:30pm", desc: "Akureyri botanical garden — free", note: "World's most northerly botanical garden. Remarkable in full summer bloom." },
        { time: "7:00pm", desc: "Dinner — cook in guesthouse kitchen or reindeer burger at Backpackers restaurant (~$20pp)" },
      ],
      hikes: [],
      excursions: [
        { name: "Whale Watching — Akureyri", operator: "Whale Watching Akureyri (whalewatchingakureyri.is)", price: "~$90pp", duration: "3 hrs", desc: "Eyjafjörður is Iceland's longest fjord and one of Europe's most reliable whale-watching spots. July = peak humpback and minke whale season. Sighting success rate ~95%. Tours depart from the city harbour — no transfer needed. Humpbacks are regularly seen breaching and bubble-net feeding." },
      ],
      tips: ["Akureyri is a great rest stop after two days on F-roads. Long shower, full laundry, proper resupply.", "The botanical garden at 65°N latitude blooms beautifully in July — a strange and lovely juxtaposition with the volcanic landscape."],
      warnings: [],
      costs: { accommodation: 55, food: 26, activities: 90 }
    },
    {
      num: 13, date: "Jul 12", title: "Kolugljúfur Canyon + Hólar Forest Camp",
      sleep: "camp", accommodation: "Hólar Campground",
      tags: ["camp", "hike"],
      costPP: 46,
      lat: 65.7371, lng: -19.1196,
      color: "#22c55e",
      summary: "Kolugljúfur hidden canyon waterfall. Hólar ancient cathedral village. Sheltered forest campsite.",
      schedule: [
        { time: "9:00am", desc: "Depart Akureyri west on Ring Road" },
        { time: "10:30am", desc: "CALL Hólar campsite first: +354 899 3231 to confirm water is operational" },
        { time: "11:30am", desc: "Kolugljúfur canyon — free stop", note: "Route 715 south off Ring Road. 30-60 min walk." },
        { time: "1:00pm", desc: "Drive south to Hólar í Hjaltadal (~45 min)" },
        { time: "2:00pm", desc: "Arrive Hólar — explore cathedral grounds (free)" },
        { time: "3:00pm", desc: "Set up camp in birch forest. Cook dinner." },
        { time: "Evening", desc: "Very quiet evening. Read, plan Snæfellsnes route." },
      ],
      hikes: [
        { name: "Kolugljúfur Canyon Walk", distance: "1-2km", difficulty: "Easy", gain: "50m", time: "30-60 min", desc: "A hidden gorge carved deep into red-orange rock with multiple waterfalls dropping into the canyon. One shoots water upward in strong wind, creating a natural mist wall. One of the best free stops of the entire trip — known to almost no tourists outside Iceland. No guardrails: take care near the edge. Free parking." },
      ],
      excursions: [],
      tips: ["Hólar is Iceland's oldest cathedral village and one-time religious centre. The red sandstone cathedral dates from 1763. Walk the grounds freely.", "This is a deliberate slow day between two intense highland sections. Embrace it."],
      warnings: ["CALL Hólar campsite (+354 899 3231) before leaving Akureyri. A May 2026 review flagged water disconnection. If confirmed down, backup: Hvammstangi municipal campsite (~50 min west on Ring Road)."],
      costs: { accommodation: 14, food: 18, activities: 0 }
    },
    {
      num: 14, date: "Jul 13", title: "Snæfellsnes — Kirkjufell + Freezer Hostel",
      sleep: "hostel", accommodation: "The Freezer Hostel, Rif",
      tags: ["hostel", "hike"],
      costPP: 78,
      lat: 64.9222, lng: -23.8194,
      color: "#4a9eff",
      summary: "Long drive to Snæfellsnes. Ytri Tunga seal colony. Kirkjufell mountain at midnight sun.",
      schedule: [
        { time: "8:00am", desc: "Depart Hólar. Drive south then west to Snæfellsnes (~220km, ~3 hrs)" },
        { time: "1:00pm", desc: "Ytri Tunga seal colony beach", note: "FREE. Harbor seals lounge on rocks completely unbothered. Walk boardwalk to find them." },
        { time: "2:00pm", desc: "Kirkjufell mountain + Kirkjufellsfoss waterfall viewpoint", note: "FREE. Iceland's most photographed mountain. Classic waterfall-in-foreground composition." },
        { time: "4:30pm", desc: "Check in The Freezer Hostel, Rif", note: "thefreezerhostel.com. Owner Kári plays live guitar evenings." },
        { time: "6:00pm", desc: "Cook dinner in hostel kitchen" },
        { time: "11:30pm", desc: "Drive back to Kirkjufell for midnight sun golden light", note: "10 min from hostel. Bring camera. The mountain glows gold." },
      ],
      hikes: [],
      excursions: [],
      tips: ["The midnight sun light on Kirkjufell is genuinely one of the great photographic moments of Iceland. Don't skip the midnight drive back.", "The Freezer is a converted fish-freezing plant. Art on every wall, acoustic music most evenings, owner is genuinely interesting. Stay up late talking to him."],
      warnings: [],
      costs: { accommodation: 45, food: 18, activities: 0, fuel: 55 }
    },
    {
      num: 15, date: "Jul 14", title: "Snæfellsjökull + Seltún → KEF Fly Home",
      sleep: "—", accommodation: "Fly home",
      tags: ["hike"],
      costPP: 38,
      lat: 63.8958, lng: -22.0548,
      color: "#a78bfa",
      summary: "Arnarstapi coastal trail. Snæfellsjökull glacier tip. Seltún geothermal on Reykjanes. Return truck to KEF.",
      schedule: [
        { time: "7:30am", desc: "Arnarstapi — coastal trail + Gatklettur arch hike" },
        { time: "9:30am", desc: "Hellnar viewpoint + lava shore walk" },
        { time: "10:30am", desc: "Drive to Snæfellsjökull NP glacier tip — free drive-in" },
        { time: "12:00pm", desc: "Drive south to Reykjanes peninsula (~2hrs)" },
        { time: "2:00pm", desc: "Seltún geothermal area — 30 min boardwalk", note: "FREE. Bubbling mud pots, steaming vents, mineral-stained earth. En route to KEF." },
        { time: "3:30pm", desc: "Return truck to KEF rental lot", note: "Allow 2.5hrs before flight. Clean truck bed." },
        { time: "Airport", desc: "Duty-free at KEF. VAT refund desk if eligible. Depart." },
      ],
      hikes: [
        { name: "Arnarstapi–Hellnar Coastal Trail + Gatklettur", distance: "5km RT", difficulty: "Easy", gain: "50m", time: "1.5 hrs", desc: "Walk the coastal path between the two villages past basalt sea stacks, sea arches, caves, and seabird colonies. The highlight is Gatklettur — a circular arch rock naturally hollowed by waves. Fulmars, kittiwakes, and Arctic terns everywhere. One of the best free hikes on Snæfellsnes." },
      ],
      excursions: [],
      tips: ["Return truck with at least 2.5hrs before your flight. KEF is fast but don't cut it close on the last day.", "Duty-free at KEF is genuinely cheap for Icelandic spirits, chocolate, and wool products."],
      warnings: [],
      costs: { accommodation: 0, food: 18, activities: 0 }
    },
  ],

  // Geographic region groupings for route filter
  regions: {
    south: [1, 2, 3, 4, 5, 6, 7],
    east: [7, 8, 9],
    north: [10, 11, 12, 13],
    west: [13, 14, 15],
  },

  budget: {
    fixed: [
      { label: "4x4 truck rental (15 days, F-road insurance)", sub: "~$90/day", pp: 675, total: 1350 },
      { label: "Iceland Camping Card (2-person, 28 nights)", sub: "campingcard.is", pp: 94, total: 187 },
      { label: "Travel insurance (adventure coverage)", sub: "Recommended: World Nomads", pp: 60, total: 120 },
    ],
    accommodation: [
      { label: "Hostel nights × 7 (avg $47pp)", sub: "Loft HI, Midgard, Vík HI, Höfn HI, East GH, Akureyri, Freezer", pp: 329, total: 658 },
      { label: "Camp nights × 7 (avg $17pp)", sub: "Landmannalaugar, Þakgil, Blágil, Skaftafell, Stafafell, Hlíð, Dreki", pp: 119, total: 238 },
    ],
    food: [
      { label: "15 days self-catering (avg $22/day)", sub: "Bónus shops in Reykjavík, Egilsstaðir. Cook from truck.", pp: 330, total: 660 },
    ],
    activities: [
      { label: "Ice axe climbing — Sólheimajökull", sub: "mountainguides.is — BOOK NOW", pp: 218, total: 436 },
      { label: "Blue Ice hike — Skaftafell", sub: "mountainguides.is", pp: 95, total: 190 },
      { label: "Katla ice cave super-jeep", sub: "troll.is / katlatrack.is", pp: 90, total: 180 },
      { label: "Jökulsárlón kayak tour", sub: "icelagoon.is", pp: 98, total: 196 },
      { label: "Whale watching — Akureyri", sub: "whalewatchingakureyri.is", pp: 90, total: 180 },
      { label: "Sky Lagoon (Saman pass)", sub: "skylagoon.com", pp: 100, total: 200 },
      { label: "Þórsmörk Sterna bus return", sub: "sterna.is", pp: 44, total: 88 },
      { label: "Earth Lagoon Mývatn", sub: "earthlagoon.is — confirm reopening", pp: 64, total: 128 },
      { label: "Hallgrímskirkja tower", sub: "", pp: 11, total: 22 },
    ],
    fuel: [
      { leg: "KEF → Reykjavík + errands", km: 80, cost: 10 },
      { leg: "Day 2: Reykjavík → Háifoss → Landmannalaugar", km: 210, cost: 26 },
      { leg: "Day 3: Midgard → Þórsmörk area → Þakgil", km: 60, cost: 8 },
      { leg: "Day 4: Þakgil → Vík area", km: 70, cost: 9 },
      { leg: "Day 5: Vík → Laki F206/F207 → Blágil", km: 200, cost: 35 },
      { leg: "Day 6: Blágil → Sólheimajökull → Skaftafell", km: 180, cost: 22 },
      { leg: "Day 7: Skaftafell → Jökulsárlón → Höfn", km: 90, cost: 11 },
      { leg: "Day 8: Höfn → Stafafell", km: 130, cost: 16 },
      { leg: "Day 9: Stafafell → Stuðlagil → Seyðisfjörður → Egilsstaðir", km: 200, cost: 25 },
      { leg: "Day 10: Egilsstaðir → Mývatn", km: 175, cost: 22 },
      { leg: "Day 11: Mývatn → F88 → Askja → Dreki (highland)", km: 260, cost: 49 },
      { leg: "Day 12: Dreki → F88 exit → Akureyri", km: 200, cost: 25 },
      { leg: "Day 13: Akureyri → Kolugljúfur → Hólar", km: 100, cost: 13 },
      { leg: "Day 14: Hólar → Snæfellsnes", km: 220, cost: 28 },
      { leg: "Day 15: Snæfellsnes → Reykjanes → KEF", km: 200, cost: 25 },
    ],
    parking: [
      { site: "Háifoss (Road 332)", cost: 8 },
      { site: "Seljalandsfoss", cost: 4 },
      { site: "Skógafoss", cost: 4 },
      { site: "Skaftafell NP (Day 6 camp)", cost: 4 },
      { site: "Jökulsárlón", cost: 4 },
      { site: "Dyrhólaey", cost: 4 },
      { site: "Reynisfjara", cost: 4 },
      { site: "Hverfjall, Mývatn", cost: 4 },
      { site: "Stuðlagil Canyon", cost: 4 },
      { site: "Snæfellsjökull NP", cost: 4 },
      { site: "Seltún, Reykjanes", cost: 3 },
      { site: "Fjáðrárgljúfur Canyon", cost: 4 },
      { site: "Misc Ring Road pullouts", cost: 8 },
    ],
  },

  checklist: [
    {
      section: "Book immediately — do today",
      badge: "urgent",
      items: [
        { text: "Ice axe climbing — Sólheimajökull", sub: "Day 6 (Jul 5) · 4hrs on glacier · $218pp", url: "https://www.mountainguides.is" },
        { text: "Blue Ice Experience — Skaftafell", sub: "Day 6 (Jul 5) afternoon · $95pp", url: "https://www.mountainguides.is" },
        { text: "Katla ice cave super-jeep tour", sub: "Day 4 (Jul 3) · $90pp · departs Vík", url: "https://www.troll.is" },
        { text: "Jökulsárlón kayak tour", sub: "Day 7 (Jul 6) · $98pp · dry suits provided", url: "https://icelagoon.is" },
        { text: "Whale watching — Akureyri", sub: "Day 12 (Jul 11) · $90pp · 3hrs", url: "https://www.whalewatchingakureyri.is" },
        { text: "Sky Lagoon — Saman Pass", sub: "Day 1 (Jun 30) evening · $100pp", url: "https://www.skylagoon.com" },
        { text: "Loft HI Hostel, Reykjavík", sub: "Night 1 (Jun 30) · $45pp", url: "https://www.hostel.is" },
        { text: "Þórsmörk Sterna bus return", sub: "Day 3 (Jul 2) · $44pp · must pre-book", url: "https://www.sterna.is" },
        { text: "Vík HI Hostel", sub: "Night 4 (Jul 3)", url: "https://www.hostel.is" },
        { text: "Höfn HI Hostel", sub: "Night 7 (Jul 6)", url: "https://www.hostel.is" },
        { text: "Þakgil canyon campsite", sub: "Night 3 (Jul 2) · thakgil.is or +354 893 4889", url: "https://www.thakgil.is" },
      ]
    },
    {
      section: "Book within 1–2 weeks",
      badge: "soon",
      items: [
        { text: "East Guesthouse, Egilsstaðir", sub: "Night 9 (Jul 8)", url: "https://www.eastguesthouse.is" },
        { text: "Akureyri Guesthouse", sub: "Night 12 (Jul 11) · book via Booking.com" },
        { text: "The Freezer Hostel, Rif", sub: "Night 14 (Jul 13)", url: "https://www.thefreezerhostel.com" },
        { text: "Landmannalaugar parking reservation", sub: "Required 9am-4pm arrivals · fi.is", url: "https://www.fi.is/en/mountain-huts/all-mountain-huts/landmannalaugar" },
      ]
    },
    {
      section: "Purchase before departure",
      badge: "before",
      items: [
        { text: "Iceland Camping Card (2-person, 28 nights)", sub: "€179 / ~$187 · campingcard.is", url: "https://www.campingcard.is" },
        { text: "Travel insurance with adventure activity coverage", sub: "World Nomads or similar · ~$60pp" },
        { text: "Head nets × 2", sub: "Absolutely essential for Mývatn. Non-optional." },
        { text: "Water filter (Sawyer Squeeze or similar)", sub: "For Lónsöræfi and Askja trail days" },
        { text: "Blackout sleep mask × 2", sub: "Or RTT dark liner — midnight sun never gets dark in July" },
        { text: "20L fuel jerry can", sub: "For F88 Askja day — fill at Mývatn" },
      ]
    },
    {
      section: "Download before departure",
      badge: "before",
      items: [
        { text: "Parka.is app", sub: "Camera-enforced parking at ALL major Iceland sites. Pay by phone.", url: "https://parka.is" },
        { text: "112 Iceland app", sub: "One button sends GPS to emergency services. Mandatory for F-roads.", url: "https://112.is" },
        { text: "Gaia GPS or Maps.me — offline Iceland maps", sub: "Download Iceland before leaving. Covers all F-roads." },
        { text: "Bookmark road.is", sub: "Check daily for F-road conditions and closures. Critical." },
      ]
    },
    {
      section: "Call / confirm before departure",
      badge: "before",
      items: [
        { text: "Rental company — F-road insurance in writing", sub: "Confirm F88, F206/F207, F232 covered. Ask for full-size spare tire." },
        { text: "Hólar campsite water status", sub: "Call +354 899 3231 — May 2026 review flagged water disconnection" },
        { text: "Earth Lagoon Mývatn reopening confirmed", sub: "Check earthlagoon.is — 2026 renovation in progress" },
        { text: "Stafafell campsite open", sub: "Call +354 699 6684 to confirm for Jul 7" },
        { text: "Laki F206/F207 road status", sub: "Check road.is week of departure. Opens mid-July — may be tight for Jul 4" },
      ]
    },
    {
      section: "Clothing & gear",
      badge: "gear",
      items: [
        { text: "Waterproof jacket + waterproof trousers × each", sub: "Keep in truck cab at ALL times, not the truck bed" },
        { text: "Merino wool base layers × 3 sets each", sub: "Wool dries fast and doesn't smell after a long day" },
        { text: "Warm mid-layer (fleece or down puffy) × each" },
        { text: "Warm hat + gloves × each", sub: "Highlands get cold even in July — Askja especially" },
        { text: "Stiff hiking boots × each (ankle support)", sub: "Break them in before you go" },
        { text: "Dry bags for everything in truck bed" },
        { text: "Camp stove + gas canisters", sub: "Buy gas in Iceland — cannot fly with canisters" },
        { text: "Cooking pot, pan, utensils, plates, cups" },
        { text: "Sawyer Squeeze water filter", sub: "Tap water is safe. Filter for highland streams." },
        { text: "Power banks × 2", sub: "No power at Dreki or on the F-roads" },
        { text: "Tow rope + tire plug kit", sub: "F-road requirement. Non-negotiable." },
        { text: "First aid kit" },
        { text: "Sunscreen", sub: "Midnight sun = real UV exposure even at 11pm" },
      ]
    },
  ],
};
